import { Locale } from "../types";

export const copy: Record<Locale, Record<string, string>> = {
  "en-IN": {
    photo_quality: "Photo",
    quality_good: "clear",
    quality_usable: "usable",
    quality_poor: "unclear, please retake",
    quality_not_crop: "no crop seen",
    fert_rdf_note: "recommended dose {rdf}, raised or lowered by a quarter for your soil",
    fert_organic_advice: "add 5–10 tonnes of farmyard manure or compost per hectare and keep crop residue on the soil.",
    fert_confirm: "Confirm with your local KVK or agriculture officer. Source:",
    rain_7d_label: "Rain, next 7 days",
    avg_max_temp: "Avg max temp",
    soil_word: "Soil",
    water_word: "Water",
    prev_crop_word: "Last crop",
    district_main_crops: "Main crops in {district}",
    water_section: "Water for the field",
    soil_section: "Soil type",
    water_rainfed: "🌧️ Rain only",
    water_supplemental: "💧 Well, some irrigation",
    water_irrigated: "🚿 Canal or drip, full irrigation",
    soil_black: "⬛ Black (regur)",
    soil_red: "🟫 Red",
    soil_alluvial: "🟨 Alluvial",
    soil_loam: "🪨 Clay loam",
    soil_sandy: "🏜️ Light sandy",
    sym_yellow: "🟡 Yellowing leaves",
    sym_brown: "🟤 Brown spots",
    sym_powder: "⚪ White powder on leaves",
    sym_borer: "🐛 Holes or borer in stem",
    sym_wilt: "🍂 Plant wilting",
    sym_curl: "🔄 Leaf curling",
    selected_word: "selected",
    expert_code_prompt: "Enter the expert access code",
    expert_code_open: "Open expert review",
    edit_farm: "Your farm on the map",
    save_changes: "Save changes",
    farm_read_only: "This farm was added on another phone, so you can look at it here but not change it.",
    plot_corners: "{n} corners marked. Drag a yellow corner to adjust it.",
    overlay_opacity: "Satellite layer",
    home_your_farms: "Your farms",
    home_not_yours: "Added on another phone",
    nav_home: "Home",
    nav_farm: "Farm",
    nav_weather: "Weather",
    nav_crops: "Crops",
    nav_plan: "Plan",
    nav_doctor: "Doctor",
    status_accepted: "✓ Will do",
    status_declined: "Skipped",
    technical_details: "Technical details (for experts)",
    listen_today: "Listen to today's advice",
    factor_optimal: "Good fit",
    factor_compatible: "Suitable",
    factor_constrained: "Limited",
    factor_rejected: "Not suitable",
    expert_answers_title: "Answers from experts",
    uncertainty_title: "Why we're not sure",
    next_steps: "Next steps",
    causes: "Possible causes",
    findings: "Seen in photo",
    expert_waiting: "Waiting",
    expert_answered: "Answered",
    expert_submit: "Send advice",
    expert_reply: "Advice for the farmer",
    expert_none: "No cases waiting for review.",
    expert_desc: "Photos where the plant doctor wasn't sure. Have a look and reply to the farmer.",
    expert_title: "Expert review",
    chat_privacy: "Your chat is cleared after 5 minutes without use.",
    chat_q3: "Which crop should I sow now?",
    chat_q2: "When should I irrigate next?",
    chat_q1: "Can I spray tomorrow?",
    thinking: "Thinking…",
    you: "You",
    end_chat: "End chat",
    send: "Send",
    chat_placeholder: "Type a question or tap the mic…",
    chat_title: "Ask Krishi Mitra",
    sat_mean: "Mean",
    sat_share: "Share",
    sat_area: "Area",
    sat_loading: "Getting the latest clear satellite photo…",
    sat_unavailable: "No satellite photo right now",
    sat_title: "Your field from space",
    actions_title: "What to do",
    plan_question: "Your question (optional)",
    plan_working: "Preparing your plan…",
    plan_rules: "Basic plan (AI is offline)",
    plan_ai: "Written by Gemini",
    plan_desc: "Your to-do list for the next 7 days, based on your weather, soil, satellite photo and crop choice.",
    plan_title: "Field action plan",
    cancel: "Cancel",
    edit: "Edit",
    ec_label: "EC (dS/m)",
    ph_label: "pH",
    oc_label: "Organic carbon",
    k_label: "Potassium (K)",
    p_label: "Phosphorus (P)",
    n_label: "Nitrogen (N)",
    rating_high: "High",
    rating_medium: "Medium",
    rating_low: "Low",
    fert_organic_low: "Organic carbon is low:",
    fert_rhizobium: "Legume: treat seed with Rhizobium culture before sowing.",
    fert_note_test: "Based on your soil test.",
    fert_note_baseline: "Based on district average soil values. Upload your Soil Health Card for a dose specific to your farm.",
    fert_dose: "Dose (kg/ha)",
    fert_bags: "bags",
    fert_topdress: "Top dressing, 30–45 days after sowing",
    fert_basal: "At sowing",
    fert_total: "Total for your farm",
    fert_crop: "Crop",
    fert_title: "Fertilizer plan",
    soil_profile_note: "Your own soil test is used first. Anything missing comes from the district average.",
    soil_tested_on: "Tested",
    soil_uncertain: "Unclear on the card, please check",
    soil_review: "Check the values read from the card, correct any mistakes, then save.",
    soil_extracting: "Reading the card…",
    soil_save: "Save soil test",
    soil_manual: "Enter values",
    soil_upload_hint: "A photo or PDF is fine. We read the numbers, you check them before saving.",
    soil_source_unknown: "Not available",
    soil_source_district_baseline: "District average",
    soil_source_soil_test: "Soil test",
    soil_title: "Soil health & fertilizer",
    root_zone: "Root zone",
    top_soil: "Top soil",
    soil_moisture_label: "Soil moisture (estimate)",
    disease_window: "Disease risk",
    loading: "Loading…",
    expert_review_link: "Expert review",
    feat_voice: "Voice in 5 languages",
    feat_doctor: "Photo-based plant doctor",
    feat_soil: "Soil card reader & fertilizer plan",
    feat_crops: "Crop recommendations with reasons",
    feat_weather: "7-day forecast & field-work advice",
    home_no_crops: "No crop fits this season with your water and soil.",
    home_now: "Now",
    home_view_all: "View all",
    home_top_crops: "Best crops this season",
    home_delete_confirm: "Delete this farm? This cannot be undone.",
    home_delete: "Delete",
    home_new_farm: "New farm",
    home_add_farm: "Add your farm",
    home_no_farm_desc: "Add your farm with a PIN code or GPS. You'll get the week's weather, what to do in the field, and which crops suit you.",
    home_no_farm_title: "Weather and crop advice for your own field",
    home_today: "Today on your farm",
    temperature_window: "Heat and cold",
    farm_forecast_title: "Day by day",
    col_day: "Day",
    col_rain: "Rain",
    col_chance: "Chance",
    col_temp: "Max / Min",
    col_wind: "Wind",
    col_humidity: "Humidity",
    day_forecast_for: "Forecast for {day}",
    day_back_today: "← Today",
    day_tap_hint: "Tap a day to see its weather",
    rain_jar_scale: "Full jar = 25 mm or more rain",
    col_gusts: "Gusts",
    col_et0: "Crop water use (ET₀)",
    col_spray: "Spray",
    water_balance: "Rain vs crop's need",
    past_7d_rain: "Rain, last 7 days",
    weather_updated: "Updated",
    weather_source_note: "Forecast for your exact location from Open-Meteo. It updates on its own every 3 hours.",
    planning_season: "Planning season",
    current_season_tag: "current",
    scene_pending: "Scene date not available",
    forecast_pending: "Fetching forecast…",
    st_ready: "Ready",
    st_marginal: "Marginal",
    st_wait: "Wait",
    st_safe: "Safe",
    st_caution: "Caution",
    st_avoid: "Avoid",
    st_not_needed: "Not needed",
    st_monitor: "Monitor",
    st_irrigate: "Irrigate",
    st_conserve: "Save moisture",
    st_low: "Low",
    st_moderate: "Moderate",
    st_high: "High",
    st_normal: "Normal",
    st_cold: "Cold",
    st_unknown: "No data",
    brand_title: "KISANAI",
    brand_sub: "Weather & crop advice",
    start: "Add your farm",
    advice: "Field plan",
    weather: "Weather",
    crops: "Crop advice",
    diagnose: "Plant Doctor",
    expert: "Expert review",
    live: "Live data",
    farm: "Your farm",
    save: "Save and see the weather",
    refresh: "Refresh",
    generate: "Make my plan",
    upload_photo: "Check this photo",
    soil_upload: "Upload Soil Health Card",
    uncertain: "Uncertain",
    listen: "Listen",
    record: "Speak",
    stop: "Stop",
    accept: "Will do",
    decline: "Skip",
    select_lang_title: "Choose Your Language",
    select_lang_sub: "Pick the language you want to read and hear advice in.",
    change_lang: "Language",
    wind_speed: "Wind Speed",
    humidity: "Relative Humidity",
    rainfall_today: "Rainfall Today",
    forecast_7d: "7-Day Rain Total",
    soil_status: "Soil Moisture",
    normal_weather: "No weather warnings",
    normal_weather_desc: "IMD has no severe warning for your district right now.",
    state_label: "State",
    district_label: "District",
    village_label: "Village / Taluka (Optional)",
    district_placeholder: "Enter district or use PIN code",
    village_placeholder: "Enter village or taluka",
    current_crop_label: "Current Standing Crop",
    previous_crop_label: "Previous Season Crop (For Rotation Planning)",
    select_crop_empty: "-- Select (None / Planning New Crop) --",
    select_prev_crop_empty: "-- Select (None / Fallow) --",
    custom_crop_opt: "✍️ Other / Custom Crop...",
    fallow_opt: "None / Fallow",
    affected_crop_title: "Affected Crop (Optional)",
    auto_detect_crop_opt: "-- Not sure, let the photo decide --",
    growth_stage_label: "Crop Growth Stage (Optional)",
    auto_detect_stage_opt: "-- Not sure --",
    stage_seedling: "Seedling (0-20 days)",
    stage_vegetative: "Vegetative Growth",
    stage_flowering: "Flowering / Squaring",
    stage_pod_filling: "Boll / Pod Filling",
    stage_maturity: "Pre-Harvest Maturity",
    observed_symptoms_title: "Observed Symptoms (Optional)",
    select_symptom_opt: "-- Select symptom from list (optional) --",
    additional_notes: "Additional Observations (Optional)",
    notes_placeholder: "e.g. Started after recent heavy rain",
    ndmi_label_short: "Leaf water (NDMI)",
    ndvi_label_short: "Crop greenness (NDVI)",
    water_stress: "Water Stress",
    farm_explainer_title: "Find your farm",
    farm_explainer_desc: "Type your 6-digit PIN code or tap GPS. Then tap 3 to 5 corners of your field on the map and we'll work out the area.",
    diagnose_explainer_title: "Plant doctor",
    diagnose_explainer_desc: "Take a clear photo of the sick leaf or pest. We'll tell you what we see, what might be causing it and what's safe to do. If we're not sure, an expert will look at it.",
    tap_photo_prompt: "Tap to take or choose a photo of the sick leaf",
    photo_format_hint: "PNG, JPG or WebP supported",
    visible_findings_title: "What we see",
    plausible_causes_title: "What it might be",
    safe_next_steps_title: "What to do next",
    escalated_badge: "👨‍🔬 Sent to an expert",
    analyzing_leaf: "Looking at your photo…",
    analyzing_leaf_desc: "Checking the leaf for spots, colour changes and pests.",
    add_farm_first: "Add your farm first",
    add_farm_first_desc: "Add your farm so the advice matches your field.",
    evidence_strip_title: "Last updated",
    latest_weather_obs: "Weather",
    soil_profile_title: "Soil",
    sowing_window: "Sowing",
    spraying_window: "Spraying",
    irrigation_advisory: "Watering",
    drainage_alert: "Waterlogging",
    table_status: "Condition",
    table_range: "Range",
    crop_rec_sub: "Based on your soil, your water, the coming week's weather and what you grew last.",
    rec_crops_heading: "Good crops for your field",
    unsuitable_crops_heading: "Not a good fit right now",
    match_score: "match",
    evidence_cov: "of the data available",
    decision_factors: "Why",
    data_used: "Based on",
    reasoning: "Reason",
    remedy: "What you can do",
    sources_badge: "Based on",
    loading_crop_recs: "Working out the best crops for your field…",
    no_crops_found: "None of the crops suit this season with your water and soil.",
    why_unsuitable: "Why not:",
    view_factors_btn: "See why",
    hide_factors_btn: "Hide reasons",
    view_unsuitable_btn: "Crops that don't fit",
    hide_unsuitable_btn: "Hide",
    step_farm: "1. Field Plot",
    step_weather: "2. Local Weather",
    step_soil: "3. Soil Health",
    step_crops: "4. Crop Recs",
    step_advice: "5. Field Plan",
    plant_doctor: "Plant Doctor",
    btn_proceed_weather: "Proceed to Local Weather →",
    btn_proceed_soil: "Proceed to Soil Health (Optional) →",
    btn_skip_soil: "Skip Soil Test & See Crops →",
    btn_proceed_crops: "Proceed to Crop Recommendations →",
    btn_proceed_plan: "Proceed to Field Action Plan →",
    btn_proceed_doctor: "Proceed to Crop Doctor →",
    btn_back_farm: "← Back to Field Plot",
    btn_back_weather: "← Back to Local Weather",
    btn_back_soil: "← Back to Soil Health",
    btn_back_crops: "← Back to Crop Recs",
    btn_back_plan: "← Back to Field Plan",
    pincode_label: "PIN code",
    pincode_placeholder: "6-digit PIN code, e.g. 445001",
    pincode_btn: "Find Location",
    pincode_searching: "Searching PIN...",
    plot_farm_boundary: "Mark your field on the map",
    plot_helper_tip: "Tap the corners of your field on the map. The area is worked out for you.",
    plot_auto_1ac: "1-Acre Box",
    plot_auto_2ac: "2.5-Acre Box",
    plot_clear: "Clear Points"
  },
  "hi-IN": {
    photo_quality: "फोटो",
    quality_good: "साफ़",
    quality_usable: "ठीक",
    quality_poor: "अस्पष्ट, फिर से लें",
    quality_not_crop: "फसल नहीं दिखी",
    fert_rdf_note: "अनुशंसित मात्रा {rdf}, आपकी मिट्टी के अनुसार एक-चौथाई कम या ज़्यादा",
    fert_organic_advice: "प्रति हेक्टेयर 5–10 टन गोबर खाद या कंपोस्ट डालें और फसल अवशेष मिट्टी पर रहने दें।",
    fert_confirm: "अपने स्थानीय KVK या कृषि अधिकारी से पुष्टि करें। स्रोत:",
    rain_7d_label: "अगले 7 दिन की बारिश",
    avg_max_temp: "औसत अधिकतम तापमान",
    soil_word: "मिट्टी",
    water_word: "पानी",
    prev_crop_word: "पिछली फसल",
    district_main_crops: "{district} की मुख्य फसलें",
    water_section: "खेत के लिए पानी",
    soil_section: "मिट्टी का प्रकार",
    water_rainfed: "🌧️ केवल बारिश",
    water_supplemental: "💧 कुआं, थोड़ी सिंचाई",
    water_irrigated: "🚿 नहर या ड्रिप, पूरी सिंचाई",
    soil_black: "⬛ काली मिट्टी",
    soil_red: "🟫 लाल मिट्टी",
    soil_alluvial: "🟨 जलोढ़ मिट्टी",
    soil_loam: "🪨 दोमट मिट्टी",
    soil_sandy: "🏜️ हल्की रेतीली",
    sym_yellow: "🟡 पत्तियां पीली",
    sym_brown: "🟤 भूरे धब्बे",
    sym_powder: "⚪ पत्तियों पर सफेद पाउडर",
    sym_borer: "🐛 तने में छेद या कीड़ा",
    sym_wilt: "🍂 पौधा मुरझाना",
    sym_curl: "🔄 पत्ती मुड़ना",
    selected_word: "चुना",
    expert_code_prompt: "विशेषज्ञ प्रवेश कोड डालें",
    expert_code_open: "विशेषज्ञ समीक्षा खोलें",
    edit_farm: "नक्शे पर आपका खेत",
    save_changes: "बदलाव सहेजें",
    farm_read_only: "यह खेत दूसरे फोन से जोड़ा गया है, इसलिए आप इसे देख सकते हैं पर बदल नहीं सकते।",
    plot_corners: "{n} कोने चिह्नित। ठीक करने के लिए पीला कोना खींचें।",
    overlay_opacity: "उपग्रह परत",
    home_your_farms: "आपके खेत",
    home_not_yours: "दूसरे फोन से जोड़ा गया",
    nav_home: "होम",
    nav_farm: "खेत",
    nav_weather: "मौसम",
    nav_crops: "फसलें",
    nav_plan: "योजना",
    nav_doctor: "डॉक्टर",
    status_accepted: "✓ करूंगा",
    status_declined: "छोड़ा",
    technical_details: "तकनीकी विवरण (विशेषज्ञों के लिए)",
    listen_today: "आज की सलाह सुनें",
    factor_optimal: "उत्तम",
    factor_compatible: "उपयुक्त",
    factor_constrained: "सीमित",
    factor_rejected: "अनुपयुक्त",
    expert_answers_title: "विशेषज्ञों के उत्तर",
    uncertainty_title: "हम पक्का क्यों नहीं हैं",
    next_steps: "अगले कदम",
    causes: "संभावित कारण",
    findings: "फोटो में दिखा",
    expert_waiting: "प्रतीक्षा में",
    expert_answered: "उत्तर दिया",
    expert_submit: "सलाह भेजें",
    expert_reply: "किसान के लिए सलाह",
    expert_none: "समीक्षा के लिए कोई मामला नहीं।",
    expert_desc: "वे फोटो जिनमें पौध डॉक्टर पक्का नहीं था। देखकर किसान को जवाब दें।",
    expert_title: "विशेषज्ञ समीक्षा",
    chat_privacy: "5 मिनट उपयोग न होने पर बातचीत मिट जाती है।",
    chat_q3: "अभी कौन सी फसल बोऊं?",
    chat_q2: "अगली सिंचाई कब करूं?",
    chat_q1: "क्या मैं कल छिड़काव कर सकता हूँ?",
    thinking: "सोच रहा है…",
    you: "आप",
    end_chat: "बातचीत समाप्त",
    send: "भेजें",
    chat_placeholder: "प्रश्न लिखें या माइक दबाएं…",
    chat_title: "कृषि मित्र से पूछें",
    sat_mean: "औसत",
    sat_share: "हिस्सा",
    sat_area: "क्षेत्र",
    sat_loading: "नवीनतम साफ़ उपग्रह फोटो ला रहे हैं…",
    sat_unavailable: "अभी उपग्रह फोटो नहीं है",
    sat_title: "अंतरिक्ष से आपका खेत",
    actions_title: "क्या करें",
    plan_question: "आपका प्रश्न (वैकल्पिक)",
    plan_working: "आपकी योजना तैयार हो रही है…",
    plan_rules: "साधारण योजना (AI अभी बंद है)",
    plan_ai: "Gemini ने लिखा",
    plan_desc: "अगले 7 दिनों के काम, आपके मौसम, मिट्टी, उपग्रह फोटो और फसल के आधार पर।",
    plan_title: "खेत कार्य योजना",
    cancel: "रद्द करें",
    edit: "बदलें",
    ec_label: "EC (dS/m)",
    ph_label: "pH",
    oc_label: "जैविक कार्बन",
    k_label: "पोटाश (K)",
    p_label: "फॉस्फोरस (P)",
    n_label: "नाइट्रोजन (N)",
    rating_high: "अधिक",
    rating_medium: "मध्यम",
    rating_low: "कम",
    fert_organic_low: "जैविक कार्बन कम है:",
    fert_rhizobium: "दलहन: बुवाई से पहले बीज को राइजोबियम कल्चर से उपचारित करें।",
    fert_note_test: "आपके मृदा परीक्षण पर आधारित।",
    fert_note_baseline: "जिला औसत मृदा मानों पर आधारित। अपने खेत की सटीक मात्रा के लिए मृदा कार्ड अपलोड करें।",
    fert_dose: "मात्रा (किग्रा/हे)",
    fert_bags: "बोरी",
    fert_topdress: "ऊपरी खाद, बुवाई के 30–45 दिन बाद",
    fert_basal: "बुवाई के समय",
    fert_total: "आपके खेत के लिए कुल",
    fert_crop: "फसल",
    fert_title: "उर्वरक योजना",
    soil_profile_note: "पहले आपकी मिट्टी जांच ली जाती है। जो नहीं है वह जिले के औसत से।",
    soil_tested_on: "परीक्षण",
    soil_uncertain: "कार्ड पर अस्पष्ट, कृपया जांचें",
    soil_review: "कार्ड से पढ़े मान जांचें, गलती सुधारें, फिर सहेजें।",
    soil_extracting: "कार्ड पढ़ा जा रहा है…",
    soil_save: "मृदा परीक्षण सहेजें",
    soil_manual: "मान दर्ज करें",
    soil_upload_hint: "फोटो या PDF चलेगा। हम अंक पढ़ेंगे, सहेजने से पहले आप जांच लें।",
    soil_source_unknown: "उपलब्ध नहीं",
    soil_source_district_baseline: "जिला औसत",
    soil_source_soil_test: "मृदा परीक्षण",
    soil_title: "मृदा स्वास्थ्य व उर्वरक",
    root_zone: "जड़ क्षेत्र",
    top_soil: "ऊपरी मिट्टी",
    soil_moisture_label: "मिट्टी की नमी (अनुमान)",
    disease_window: "रोग का खतरा",
    loading: "लोड हो रहा है…",
    expert_review_link: "विशेषज्ञ समीक्षा",
    feat_voice: "5 भाषाओं में आवाज़",
    feat_doctor: "फोटो से पौध चिकित्सक",
    feat_soil: "मृदा कार्ड रीडर व उर्वरक योजना",
    feat_crops: "कारण सहित फसल सिफारिशें",
    feat_weather: "7-दिन पूर्वानुमान व खेती कार्य सलाह",
    home_no_crops: "इस मौसम में आपके पानी और मिट्टी से कोई फसल मेल नहीं खाती।",
    home_now: "अभी",
    home_view_all: "सभी देखें",
    home_top_crops: "इस मौसम की सर्वोत्तम फसलें",
    home_delete_confirm: "यह खेत हटाएं? यह वापस नहीं होगा।",
    home_delete: "हटाएं",
    home_new_farm: "नया खेत",
    home_add_farm: "अपना खेत जोड़ें",
    home_no_farm_desc: "पिन कोड या GPS से खेत जोड़ें। आपको हफ्ते का मौसम, खेत में क्या करना है और कौन सी फसल ठीक है, सब मिलेगा।",
    home_no_farm_title: "आपके अपने खेत के लिए मौसम और फसल सलाह",
    home_today: "आज आपके खेत पर",
    temperature_window: "गर्मी और ठंड",
    farm_forecast_title: "रोज़ का मौसम",
    col_day: "दिन",
    col_rain: "वर्षा",
    col_chance: "संभावना",
    col_temp: "अधिकतम / न्यूनतम",
    col_wind: "हवा",
    col_humidity: "नमी",
    day_forecast_for: "{day} का पूर्वानुमान",
    day_back_today: "← आज",
    day_tap_hint: "किसी दिन पर टैप करें, उस दिन का मौसम दिखेगा",
    rain_jar_scale: "भरा बर्तन = 25 मिमी या अधिक बारिश",
    col_gusts: "झोंके",
    col_et0: "फसल जल उपयोग (ET₀)",
    col_spray: "छिड़काव",
    water_balance: "बारिश बनाम फसल की ज़रूरत",
    past_7d_rain: "पिछले 7 दिनों की वर्षा",
    weather_updated: "अपडेट",
    weather_source_note: "Open-Meteo से आपकी जगह का पूर्वानुमान। हर 3 घंटे में अपने आप अपडेट होता है।",
    planning_season: "योजना मौसम",
    current_season_tag: "वर्तमान",
    scene_pending: "दृश्य तिथि उपलब्ध नहीं",
    forecast_pending: "पूर्वानुमान लाया जा रहा है…",
    st_ready: "तैयार",
    st_marginal: "सीमित",
    st_wait: "रुकें",
    st_safe: "सुरक्षित",
    st_caution: "सावधानी",
    st_avoid: "न करें",
    st_not_needed: "आवश्यक नहीं",
    st_monitor: "निगरानी",
    st_irrigate: "सिंचाई करें",
    st_conserve: "नमी बचाएं",
    st_low: "कम",
    st_moderate: "मध्यम",
    st_high: "अधिक",
    st_normal: "सामान्य",
    st_cold: "ठंड",
    st_unknown: "डेटा नहीं",
    brand_title: "KISANAI",
    brand_sub: "मौसम व फसल सलाह",
    start: "अपना खेत जोड़ें",
    advice: "खेत की योजना",
    weather: "मौसम",
    crops: "फसल सलाह",
    diagnose: "फसल डॉक्टर",
    expert: "विशेषज्ञ समीक्षा",
    live: "ताज़ा जानकारी",
    farm: "आपका खेत",
    save: "सहेजें और मौसम देखें",
    refresh: "रीफ्रेश करें",
    generate: "मेरी योजना बनाएं",
    upload_photo: "यह फोटो जांचें",
    soil_upload: "मृदा स्वास्थ्य कार्ड अपलोड करें",
    uncertain: "अनिश्चित",
    listen: "सुनें",
    record: "बोलें",
    stop: "रोकें",
    accept: "करूंगा",
    decline: "छोड़ें",
    select_lang_title: "अपनी भाषा चुनें",
    select_lang_sub: "वह भाषा चुनें जिसमें आप सलाह पढ़ना और सुनना चाहते हैं।",
    change_lang: "भाषा बदलें",
    wind_speed: "हवा की गति",
    humidity: "सापेक्ष आर्द्रता",
    rainfall_today: "आज की वर्षा",
    forecast_7d: "7-दिवसीय कुल वर्षा",
    soil_status: "मृदा नमी स्थिति",
    normal_weather: "कोई मौसम चेतावनी नहीं",
    normal_weather_desc: "IMD ने अभी आपके जिले के लिए कोई गंभीर चेतावनी नहीं दी है।",
    state_label: "राज्य",
    district_label: "जिला",
    village_label: "गाँव / तालुका (वैकल्पिक)",
    district_placeholder: "जिला दर्ज करें या पिन कोड डालें",
    village_placeholder: "गाँव अथवा तालुका दर्ज करें",
    current_crop_label: "खेत में लगी वर्तमान फसल",
    previous_crop_label: "पिछले मौसम की फसल (फसल चक्र हेतु)",
    select_crop_empty: "-- चुनें (खाली खेत / नई फसल योजना) --",
    select_prev_crop_empty: "-- चुनें (कोई नहीं / परती) --",
    custom_crop_opt: "✍️ अन्य / अलग फसल...",
    fallow_opt: "कोई नहीं / परती",
    affected_crop_title: "प्रभावित फसल (वैकल्पिक)",
    auto_detect_crop_opt: "-- पता नहीं, फोटो से पहचानें --",
    growth_stage_label: "फसल विकास अवस्था (वैकल्पिक)",
    auto_detect_stage_opt: "-- पता नहीं --",
    stage_seedling: "अंकुरण / पौधा (0-20 दिन)",
    stage_vegetative: "वानस्पतिक वृद्धि",
    stage_flowering: "फूल / कली आना",
    stage_pod_filling: "फल / फली / गूलर भरना",
    stage_maturity: "परिपक्वता / कटाई पूर्व",
    observed_symptoms_title: "देखे गए लक्षण (वैकल्पिक)",
    select_symptom_opt: "-- सूची से लक्षण चुनें (वैकल्पिक) --",
    additional_notes: "अतिरिक्त विवरण (वैकल्पिक)",
    notes_placeholder: "उदा. हालिया भारी बारिश के बाद शुरू हुआ",
    ndmi_label_short: "पत्तियों में पानी (NDMI)",
    ndvi_label_short: "फसल की हरियाली (NDVI)",
    water_stress: "जल तनाव",
    farm_explainer_title: "अपना खेत ढूंढें",
    farm_explainer_desc: "अपना 6 अंकों का पिन कोड लिखें या GPS दबाएं। फिर नक्शे पर खेत के 3 से 5 कोने दबाएं, क्षेत्रफल हम निकाल देंगे।",
    diagnose_explainer_title: "पौधों का डॉक्टर",
    diagnose_explainer_desc: "बीमार पत्ती या कीड़े की साफ़ फोटो लें। हम बताएंगे क्या दिख रहा है, कारण क्या हो सकता है और क्या करना सुरक्षित है। पक्का न हो तो विशेषज्ञ देखेंगे।",
    tap_photo_prompt: "बीमार पत्ती की फोटो लेने या चुनने के लिए दबाएं",
    photo_format_hint: "PNG, JPG या WebP समर्थित",
    visible_findings_title: "क्या दिख रहा है",
    plausible_causes_title: "क्या हो सकता है",
    safe_next_steps_title: "आगे क्या करें",
    escalated_badge: "👨‍🔬 विशेषज्ञ को भेजा गया",
    analyzing_leaf: "आपकी फोटो देख रहे हैं…",
    analyzing_leaf_desc: "पत्ती पर धब्बे, रंग बदलाव और कीड़े देख रहे हैं।",
    add_farm_first: "पहले अपना खेत जोड़ें",
    add_farm_first_desc: "अपना खेत जोड़ें ताकि सलाह आपके खेत के हिसाब से हो।",
    evidence_strip_title: "आखिरी अपडेट",
    latest_weather_obs: "मौसम",
    soil_profile_title: "मिट्टी",
    sowing_window: "बुवाई",
    spraying_window: "छिड़काव",
    irrigation_advisory: "सिंचाई",
    drainage_alert: "जलभराव",
    table_status: "हालत",
    table_range: "सीमा",
    crop_rec_sub: "आपकी मिट्टी, पानी, अगले हफ्ते के मौसम और पिछली फसल के आधार पर।",
    rec_crops_heading: "आपके खेत के लिए अच्छी फसलें",
    unsuitable_crops_heading: "अभी सही नहीं",
    match_score: "मेल",
    evidence_cov: "जानकारी उपलब्ध",
    decision_factors: "क्यों",
    data_used: "आधार",
    reasoning: "कारण",
    remedy: "आप क्या कर सकते हैं",
    sources_badge: "आधार",
    loading_crop_recs: "आपके खेत के लिए सही फसलें देख रहे हैं…",
    no_crops_found: "इस मौसम में आपके पानी और मिट्टी के साथ कोई फसल ठीक नहीं बैठती।",
    why_unsuitable: "क्यों नहीं:",
    view_factors_btn: "कारण देखें",
    hide_factors_btn: "कारण छिपाएं",
    view_unsuitable_btn: "जो फसलें ठीक नहीं",
    hide_unsuitable_btn: "छिपाएं",
    step_farm: "1. खेत सीमा",
    step_weather: "2. स्थानीय मौसम",
    step_soil: "3. मृदा स्वास्थ्य",
    step_crops: "4. फसल अनुशंसा",
    step_advice: "5. कार्य योजना",
    plant_doctor: "पौधा डॉक्टर",
    btn_proceed_weather: "स्थानीय मौसम देखें →",
    btn_proceed_soil: "मृदा स्वास्थ्य देखें (वैकल्पिक) →",
    btn_skip_soil: "मृदा जांच छोड़ें और फसलें देखें →",
    btn_proceed_crops: "फसल अनुशंसाएँ देखें →",
    btn_proceed_plan: "खेत कार्य योजना देखें →",
    btn_proceed_doctor: "फसल डॉक्टर पर जाएँ →",
    btn_back_farm: "← खेत सीमा पर वापस",
    btn_back_weather: "← मौसम पर वापस",
    btn_back_soil: "← मृदा स्वास्थ्य पर वापस",
    btn_back_crops: "← फसल अनुशंसा पर वापस",
    btn_back_plan: "← कार्य योजना पर वापस",
    pincode_label: "पिन कोड",
    pincode_placeholder: "6 अंकों का पिन कोड, जैसे 445001",
    pincode_btn: "स्थान खोजें",
    pincode_searching: "पिन कोड खोज जारी...",
    plot_farm_boundary: "नक्शे पर अपना खेत चिह्नित करें",
    plot_helper_tip: "नक्शे पर खेत के कोने दबाएं। क्षेत्रफल अपने आप निकलेगा।",
    plot_auto_1ac: "1 एकड़ बॉक्स",
    plot_auto_2ac: "2.5 एकड़ बॉक्स",
    plot_clear: "बिंदु हटाएँ"
  },
  "mr-IN": {
    photo_quality: "फोटो",
    quality_good: "स्पष्ट",
    quality_usable: "चालेल",
    quality_poor: "अस्पष्ट, पुन्हा घ्या",
    quality_not_crop: "पीक दिसले नाही",
    fert_rdf_note: "शिफारस मात्रा {rdf}, तुमच्या मातीनुसार पाव भाग कमी-जास्त",
    fert_organic_advice: "हेक्टरी ५–१० टन शेणखत किंवा कंपोस्ट टाका आणि पिकाचे अवशेष जमिनीवर ठेवा.",
    fert_confirm: "तुमच्या स्थानिक KVK किंवा कृषी अधिकाऱ्याकडून खात्री करा. स्रोत:",
    rain_7d_label: "पुढील ७ दिवसांचा पाऊस",
    avg_max_temp: "सरासरी कमाल तापमान",
    soil_word: "माती",
    water_word: "पाणी",
    prev_crop_word: "मागील पीक",
    district_main_crops: "{district} मधील मुख्य पिके",
    water_section: "शेतासाठी पाणी",
    soil_section: "मातीचा प्रकार",
    water_rainfed: "🌧️ फक्त पाऊस (जिरायती)",
    water_supplemental: "💧 विहीर, थोडे सिंचन",
    water_irrigated: "🚿 कालवा किंवा ठिबक, पूर्ण सिंचन",
    soil_black: "⬛ काळी माती",
    soil_red: "🟫 तांबडी माती",
    soil_alluvial: "🟨 गाळाची माती",
    soil_loam: "🪨 पोयटा माती",
    soil_sandy: "🏜️ हलकी मुरमाड",
    sym_yellow: "🟡 पाने पिवळी",
    sym_brown: "🟤 तपकिरी ठिपके",
    sym_powder: "⚪ पानांवर पांढरी भुकटी",
    sym_borer: "🐛 खोडात छिद्र किंवा अळी",
    sym_wilt: "🍂 रोप कोमेजणे",
    sym_curl: "🔄 पाने वळणे",
    selected_word: "निवडले",
    expert_code_prompt: "तज्ञ प्रवेश कोड टाका",
    expert_code_open: "तज्ञ पुनरावलोकन उघडा",
    edit_farm: "नकाशावर तुमचे शेत",
    save_changes: "बदल जतन करा",
    farm_read_only: "हे शेत दुसऱ्या फोनवरून जोडले आहे, त्यामुळे तुम्ही ते पाहू शकता पण बदलू शकत नाही.",
    plot_corners: "{n} कोपरे आखले. बदलण्यासाठी पिवळा कोपरा ओढा.",
    overlay_opacity: "उपग्रह थर",
    home_your_farms: "तुमची शेते",
    home_not_yours: "दुसऱ्या फोनवरून जोडले",
    nav_home: "मुख्य",
    nav_farm: "शेत",
    nav_weather: "हवामान",
    nav_crops: "पिके",
    nav_plan: "आराखडा",
    nav_doctor: "डॉक्टर",
    status_accepted: "✓ करेन",
    status_declined: "वगळले",
    technical_details: "तांत्रिक तपशील (तज्ञांसाठी)",
    listen_today: "आजचा सल्ला ऐका",
    factor_optimal: "उत्तम",
    factor_compatible: "योग्य",
    factor_constrained: "मर्यादित",
    factor_rejected: "अयोग्य",
    expert_answers_title: "तज्ञांची उत्तरे",
    uncertainty_title: "आम्हाला खात्री का नाही",
    next_steps: "पुढील पावले",
    causes: "संभाव्य कारणे",
    findings: "फोटोत दिसले",
    expert_waiting: "प्रतीक्षेत",
    expert_answered: "उत्तर दिले",
    expert_submit: "सल्ला पाठवा",
    expert_reply: "शेतकऱ्यासाठी सल्ला",
    expert_none: "पुनरावलोकनासाठी प्रकरण नाही.",
    expert_desc: "ज्या फोटोंबद्दल पीक डॉक्टरला खात्री नव्हती. पाहून शेतकऱ्याला उत्तर द्या.",
    expert_title: "तज्ञ पुनरावलोकन",
    chat_privacy: "५ मिनिटे वापर न झाल्यास संवाद पुसला जातो.",
    chat_q3: "आता कोणते पीक पेरावे?",
    chat_q2: "पुढचे पाणी कधी द्यावे?",
    chat_q1: "मी उद्या फवारणी करू शकतो का?",
    thinking: "विचार करत आहे…",
    you: "तुम्ही",
    end_chat: "संवाद संपवा",
    send: "पाठवा",
    chat_placeholder: "प्रश्न लिहा किंवा माईक दाबा…",
    chat_title: "कृषी मित्राला विचारा",
    sat_mean: "सरासरी",
    sat_share: "वाटा",
    sat_area: "क्षेत्र",
    sat_loading: "नवीनतम स्वच्छ उपग्रह फोटो आणत आहोत…",
    sat_unavailable: "सध्या उपग्रह फोटो नाही",
    sat_title: "अवकाशातून तुमचे शेत",
    actions_title: "काय करावे",
    plan_question: "तुमचा प्रश्न (ऐच्छिक)",
    plan_working: "तुमचा आराखडा तयार होत आहे…",
    plan_rules: "साधी योजना (AI सध्या बंद आहे)",
    plan_ai: "Gemini ने लिहिले",
    plan_desc: "पुढच्या ७ दिवसांची कामे, तुमचे हवामान, माती, उपग्रह फोटो व पीक यावरून.",
    plan_title: "शेती कृती आराखडा",
    cancel: "रद्द करा",
    edit: "बदला",
    ec_label: "EC (dS/m)",
    ph_label: "सामू (pH)",
    oc_label: "सेंद्रिय कर्ब",
    k_label: "पालाश (K)",
    p_label: "स्फुरद (P)",
    n_label: "नत्र (N)",
    rating_high: "जास्त",
    rating_medium: "मध्यम",
    rating_low: "कमी",
    fert_organic_low: "सेंद्रिय कर्ब कमी आहे:",
    fert_rhizobium: "कडधान्य: पेरणीपूर्वी बियाण्यास रायझोबियम संवर्धन लावा.",
    fert_note_test: "तुमच्या माती परीक्षणावर आधारित.",
    fert_note_baseline: "जिल्हा सरासरी माती मूल्यांवर आधारित. तुमच्या शेतासाठी अचूक मात्रेसाठी माती पत्रिका अपलोड करा.",
    fert_dose: "मात्रा (किलो/हे)",
    fert_bags: "पोती",
    fert_topdress: "वरखत, पेरणीनंतर ३०–४५ दिवसांनी",
    fert_basal: "पेरणीच्या वेळी",
    fert_total: "तुमच्या शेतासाठी एकूण",
    fert_crop: "पीक",
    fert_title: "खत नियोजन",
    soil_profile_note: "आधी तुमचे माती परीक्षण वापरले जाते. जे नाही ते जिल्हा सरासरीतून.",
    soil_tested_on: "परीक्षण",
    soil_uncertain: "कार्डवर अस्पष्ट, कृपया तपासा",
    soil_review: "कार्डवरून वाचलेली मूल्ये तपासा, चूक दुरुस्त करा, मग जतन करा.",
    soil_extracting: "कार्ड वाचत आहे…",
    soil_save: "माती परीक्षण जतन करा",
    soil_manual: "मूल्ये भरा",
    soil_upload_hint: "फोटो किंवा PDF चालेल. आम्ही आकडे वाचू, जतन करण्यापूर्वी तुम्ही तपासा.",
    soil_source_unknown: "उपलब्ध नाही",
    soil_source_district_baseline: "जिल्हा सरासरी",
    soil_source_soil_test: "माती परीक्षण",
    soil_title: "माती आरोग्य व खत",
    root_zone: "मुळांचा भाग",
    top_soil: "वरचा थर",
    soil_moisture_label: "जमिनीतील ओल (अंदाज)",
    disease_window: "रोगाचा धोका",
    loading: "लोड होत आहे…",
    expert_review_link: "तज्ञ पुनरावलोकन",
    feat_voice: "५ भाषांमध्ये आवाज",
    feat_doctor: "फोटोवरून पीक डॉक्टर",
    feat_soil: "माती कार्ड वाचन व खत नियोजन",
    feat_crops: "कारणांसह पीक शिफारसी",
    feat_weather: "७ दिवसांचा अंदाज व शेतीकाम सल्ला",
    home_no_crops: "या हंगामात तुमच्या पाणी व मातीला कोणतेही पीक जुळत नाही.",
    home_now: "आता",
    home_view_all: "सर्व पहा",
    home_top_crops: "या हंगामातील योग्य पिके",
    home_delete_confirm: "हे शेत हटवायचे? हे पूर्ववत करता येणार नाही.",
    home_delete: "हटवा",
    home_new_farm: "नवीन शेत",
    home_add_farm: "तुमचे शेत जोडा",
    home_no_farm_desc: "पिन कोड किंवा GPS ने शेत जोडा. आठवड्याचे हवामान, शेतात काय करायचे आणि कोणती पिके योग्य ते मिळेल.",
    home_no_farm_title: "तुमच्या स्वतःच्या शेतासाठी हवामान व पीक सल्ला",
    home_today: "आज तुमच्या शेतात",
    temperature_window: "उष्णता व थंडी",
    farm_forecast_title: "दिवसानुसार",
    col_day: "दिवस",
    col_rain: "पाऊस",
    col_chance: "शक्यता",
    col_temp: "कमाल / किमान",
    col_wind: "वारा",
    col_humidity: "आर्द्रता",
    day_forecast_for: "{day} चा अंदाज",
    day_back_today: "← आज",
    day_tap_hint: "त्या दिवसाचे हवामान पाहण्यासाठी दिवसावर टॅप करा",
    rain_jar_scale: "पूर्ण भरलेले भांडे = 25 मिमी किंवा जास्त पाऊस",
    col_gusts: "झोत",
    col_et0: "पिकाचा पाणी वापर (ET₀)",
    col_spray: "फवारणी",
    water_balance: "पाऊस विरुद्ध पिकाची गरज",
    past_7d_rain: "मागील ७ दिवसांचा पाऊस",
    weather_updated: "अद्ययावत",
    weather_source_note: "Open-Meteo कडून तुमच्या जागेचा अंदाज. दर ३ तासांनी आपोआप बदलतो.",
    planning_season: "नियोजन हंगाम",
    current_season_tag: "चालू",
    scene_pending: "प्रतिमेची तारीख उपलब्ध नाही",
    forecast_pending: "अंदाज आणत आहे…",
    st_ready: "योग्य",
    st_marginal: "मर्यादित",
    st_wait: "थांबा",
    st_safe: "सुरक्षित",
    st_caution: "सावधान",
    st_avoid: "टाळा",
    st_not_needed: "गरज नाही",
    st_monitor: "लक्ष ठेवा",
    st_irrigate: "पाणी द्या",
    st_conserve: "ओलावा वाचवा",
    st_low: "कमी",
    st_moderate: "मध्यम",
    st_high: "जास्त",
    st_normal: "सामान्य",
    st_cold: "थंडी",
    st_unknown: "माहिती नाही",
    brand_title: "KISANAI",
    brand_sub: "हवामान व पीक सल्ला",
    start: "तुमचे शेत जोडा",
    advice: "शेती आराखडा",
    weather: "हवामान",
    crops: "पीक सल्ला",
    diagnose: "पीक डॉक्टर",
    expert: "तज्ञ पुनरावलोकन",
    live: "ताजी माहिती",
    farm: "तुमचे शेत",
    save: "जतन करा व हवामान पाहा",
    refresh: "पुन्हा तपासा",
    generate: "माझा आराखडा बनवा",
    upload_photo: "हा फोटो तपासा",
    soil_upload: "माती आरोग्य पत्रिका अपलोड करा",
    uncertain: "अनिश्चित",
    listen: "ऐका",
    record: "बोला",
    stop: "थांबा",
    accept: "करेन",
    decline: "वगळा",
    select_lang_title: "आपली भाषा निवडा",
    select_lang_sub: "ज्या भाषेत सल्ला वाचायचा व ऐकायचा आहे ती निवडा.",
    change_lang: "भाषा बदला",
    wind_speed: "वाऱ्याचा वेग",
    humidity: "हवेतील आर्द्रता",
    rainfall_today: "आजचा पाऊस",
    forecast_7d: "७ दिवसांचा एकूण पाऊस",
    soil_status: "जमिनीतील ओलावा",
    normal_weather: "हवामानाचा कोणताही इशारा नाही",
    normal_weather_desc: "IMD ने सध्या तुमच्या जिल्ह्यासाठी कोणताही गंभीर इशारा दिलेला नाही.",
    state_label: "राज्य",
    district_label: "जिल्हा",
    village_label: "गाव / तालुका (ऐच्छिक)",
    district_placeholder: "जिल्हा टाका किंवा पिन कोड वापरा",
    village_placeholder: "गाव किंवा तालुका टाका",
    current_crop_label: "शेतातील सध्याचे पीक",
    previous_crop_label: "मागील हंगामातील पीक (पीक फेरपालट)",
    select_crop_empty: "-- निवडा (काही नाही / नवीन पीक नियोजन) --",
    select_prev_crop_empty: "-- निवडा (काही नाही / पडीक) --",
    custom_crop_opt: "✍️ इतर / वेगळे पीक...",
    fallow_opt: "काही नाही / पडीक",
    affected_crop_title: "बाधित पीक (ऐच्छिक)",
    auto_detect_crop_opt: "-- माहीत नाही, फोटोवरून ओळखा --",
    growth_stage_label: "पिकाची वाढीची अवस्था (ऐच्छिक)",
    auto_detect_stage_opt: "-- माहीत नाही --",
    stage_seedling: "रोप अवस्था (०-२० दिवस)",
    stage_vegetative: "शाकीय वाढ",
    stage_flowering: "फुलोरा अवस्था",
    stage_pod_filling: "बोंड / शेंगा भरणे",
    stage_maturity: "पक्वता / काढणीपूर्वी",
    observed_symptoms_title: "दिसलेली लक्षणे (ऐच्छिक)",
    select_symptom_opt: "-- यादीतून लक्षण निवडा (ऐच्छिक) --",
    additional_notes: "अधिक निरीक्षणे (ऐच्छिक)",
    notes_placeholder: "उदा. पावसाच्या खंडानंतर लक्षणे दिसली",
    ndmi_label_short: "पानांमधील पाणी (NDMI)",
    ndvi_label_short: "पिकाचा हिरवेपणा (NDVI)",
    water_stress: "पाण्याचा ताण",
    farm_explainer_title: "तुमचे शेत शोधा",
    farm_explainer_desc: "तुमचा ६ अंकी पिन कोड लिहा किंवा GPS दाबा. मग नकाशावर शेताचे ३ ते ५ कोपरे दाबा, क्षेत्र आम्ही काढू.",
    diagnose_explainer_title: "पीक डॉक्टर",
    diagnose_explainer_desc: "रोगट पानाचा किंवा किडीचा स्पष्ट फोटो घ्या. काय दिसते, कारण काय असू शकते आणि काय करणे सुरक्षित आहे ते सांगू. खात्री नसेल तर तज्ञ पाहतील.",
    tap_photo_prompt: "रोगट पानाचा फोटो घेण्यासाठी किंवा निवडण्यासाठी दाबा",
    photo_format_hint: "PNG, JPG किंवा WebP समर्थित",
    visible_findings_title: "काय दिसते",
    plausible_causes_title: "काय असू शकते",
    safe_next_steps_title: "पुढे काय करावे",
    escalated_badge: "👨‍🔬 तज्ञांकडे पाठवले",
    analyzing_leaf: "तुमचा फोटो पाहत आहोत…",
    analyzing_leaf_desc: "पानावरील ठिपके, रंगातील बदल व किडी तपासत आहोत.",
    add_farm_first: "आधी तुमचे शेत जोडा",
    add_farm_first_desc: "तुमचे शेत जोडा, म्हणजे सल्ला तुमच्या शेतानुसार मिळेल.",
    evidence_strip_title: "शेवटचे अद्ययावत",
    latest_weather_obs: "हवामान",
    soil_profile_title: "माती",
    sowing_window: "पेरणी",
    spraying_window: "फवारणी",
    irrigation_advisory: "पाणी देणे",
    drainage_alert: "पाणी साचणे",
    table_status: "स्थिती",
    table_range: "मर्यादा",
    crop_rec_sub: "तुमची माती, पाणी, पुढच्या आठवड्याचे हवामान आणि मागचे पीक यावरून.",
    rec_crops_heading: "तुमच्या शेतासाठी चांगली पिके",
    unsuitable_crops_heading: "आत्ता योग्य नाही",
    match_score: "जुळणी",
    evidence_cov: "माहिती उपलब्ध",
    decision_factors: "का",
    data_used: "आधार",
    reasoning: "कारण",
    remedy: "तुम्ही काय करू शकता",
    sources_badge: "आधार",
    loading_crop_recs: "तुमच्या शेतासाठी योग्य पिके पाहत आहोत…",
    no_crops_found: "या हंगामात तुमच्या पाणी व मातीनुसार कोणतेही पीक बसत नाही.",
    why_unsuitable: "का नाही:",
    view_factors_btn: "कारणे पाहा",
    hide_factors_btn: "कारणे लपवा",
    view_unsuitable_btn: "न बसणारी पिके",
    hide_unsuitable_btn: "लपवा",
    step_farm: "१. शेत सीमा",
    step_weather: "२. स्थानिक हवामान",
    step_soil: "३. माती आरोग्य",
    step_crops: "४. पीक शिफारसी",
    step_advice: "५. कृती योजना",
    plant_doctor: "पीक डॉक्टर",
    btn_proceed_weather: "स्थानिक हवामान पहा →",
    btn_proceed_soil: "माती आरोग्य तपासा (ऐच्छिक) →",
    btn_skip_soil: "माती तपासणी वगळा व पिके पहा →",
    btn_proceed_crops: "पीक शिफारसी पहा →",
    btn_proceed_plan: "शेत कृती योजना पहा →",
    btn_proceed_doctor: "पीक डॉक्टरवर जा →",
    btn_back_farm: "← शेत सीमेवर परत",
    btn_back_weather: "← हवामानावर परत",
    btn_back_soil: "← माती आरोग्याकडे परत",
    btn_back_crops: "← पीक शिफारसीवर परत",
    btn_back_plan: "← कृती योजनेवर परत",
    pincode_label: "पिन कोड",
    pincode_placeholder: "६ अंकी पिन कोड, उदा. 445001",
    pincode_btn: "स्थान शोधा",
    pincode_searching: "पिन कोड शोधत आहे...",
    plot_farm_boundary: "नकाशावर तुमचे शेत आखा",
    plot_helper_tip: "नकाशावर शेताचे कोपरे दाबा. क्षेत्र आपोआप निघेल.",
    plot_auto_1ac: "१ एकर बॉक्स",
    plot_auto_2ac: "२.५ एकर बॉक्स",
    plot_clear: "बिंदू हटवा"
  },
  "te-IN": {
    photo_quality: "ఫోటో",
    quality_good: "స్పష్టం",
    quality_usable: "సరిపోతుంది",
    quality_poor: "స్పష్టంగా లేదు, మళ్లీ తీయండి",
    quality_not_crop: "పంట కనిపించలేదు",
    fert_rdf_note: "సిఫార్సు మోతాదు {rdf}, మీ నేల ప్రకారం పావు వంతు తగ్గింపు లేదా పెంపు",
    fert_organic_advice: "హెక్టారుకు 5–10 టన్నుల పశువుల ఎరువు లేదా కంపోస్ట్ వేయండి, పంట అవశేషాలు నేలపై ఉంచండి.",
    fert_confirm: "మీ స్థానిక KVK లేదా వ్యవసాయ అధికారితో నిర్ధారించుకోండి. మూలం:",
    rain_7d_label: "రాబోయే 7 రోజుల వర్షం",
    avg_max_temp: "సగటు గరిష్ఠ ఉష్ణోగ్రత",
    soil_word: "నేల",
    water_word: "నీరు",
    prev_crop_word: "గత పంట",
    district_main_crops: "{district} లో ప్రధాన పంటలు",
    water_section: "పొలానికి నీరు",
    soil_section: "నేల రకం",
    water_rainfed: "🌧️ వర్షం మాత్రమే",
    water_supplemental: "💧 బావి, కొంత నీటిపారుదల",
    water_irrigated: "🚿 కాలువ లేదా డ్రిప్, పూర్తి నీటిపారుదల",
    soil_black: "⬛ నల్ల రేగడి",
    soil_red: "🟫 ఎర్ర నేల",
    soil_alluvial: "🟨 ఒండ్రు నేల",
    soil_loam: "🪨 గరప నేల",
    soil_sandy: "🏜️ తేలికపాటి ఇసుక నేల",
    sym_yellow: "🟡 ఆకులు పసుపు",
    sym_brown: "🟤 గోధుమ మచ్చలు",
    sym_powder: "⚪ ఆకులపై తెల్ల పొడి",
    sym_borer: "🐛 కాండంలో రంధ్రాలు, పురుగు",
    sym_wilt: "🍂 మొక్క వాడిపోవడం",
    sym_curl: "🔄 ఆకు ముడత",
    selected_word: "ఎంచుకున్నారు",
    expert_code_prompt: "నిపుణుల యాక్సెస్ కోడ్ నమోదు చేయండి",
    expert_code_open: "నిపుణుల సమీక్ష తెరవండి",
    edit_farm: "మ్యాప్‌లో మీ పొలం",
    save_changes: "మార్పులు సేవ్ చేయండి",
    farm_read_only: "ఈ పొలం వేరే ఫోన్ నుండి జోడించారు, కాబట్టి చూడవచ్చు కానీ మార్చలేరు.",
    plot_corners: "{n} మూలలు గుర్తించారు. సరిచేయడానికి పసుపు మూలను లాగండి.",
    overlay_opacity: "ఉపగ్రహ పొర",
    home_your_farms: "మీ పొలాలు",
    home_not_yours: "వేరే ఫోన్ నుండి జోడించారు",
    nav_home: "హోమ్",
    nav_farm: "పొలం",
    nav_weather: "వాతావరణం",
    nav_crops: "పంటలు",
    nav_plan: "ప్రణాళిక",
    nav_doctor: "వైద్యుడు",
    status_accepted: "✓ చేస్తాను",
    status_declined: "వదిలేశాను",
    technical_details: "సాంకేతిక వివరాలు (నిపుణులకు)",
    listen_today: "నేటి సలహా వినండి",
    factor_optimal: "అనుకూలం",
    factor_compatible: "సరిపోతుంది",
    factor_constrained: "పరిమితం",
    factor_rejected: "అనుకూలం కాదు",
    expert_answers_title: "నిపుణుల జవాబులు",
    uncertainty_title: "మాకు ఎందుకు ఖచ్చితంగా తెలియదు",
    next_steps: "తదుపరి చర్యలు",
    causes: "సాధ్యమైన కారణాలు",
    findings: "ఫోటోలో కనిపించింది",
    expert_waiting: "వేచి ఉంది",
    expert_answered: "జవాబిచ్చారు",
    expert_submit: "సలహా పంపండి",
    expert_reply: "రైతుకు సలహా",
    expert_none: "సమీక్షకు కేసులు లేవు.",
    expert_desc: "మొక్కల డాక్టర్‌కు ఖచ్చితంగా తెలియని ఫోటోలు. చూసి రైతుకు జవాబు ఇవ్వండి.",
    expert_title: "నిపుణుల సమీక్ష",
    chat_privacy: "5 నిమిషాలు వాడకపోతే చాట్ తొలగిపోతుంది.",
    chat_q3: "ఇప్పుడు ఏ పంట వేయాలి?",
    chat_q2: "తదుపరి నీరు ఎప్పుడు పెట్టాలి?",
    chat_q1: "నేను రేపు పిచికారీ చేయవచ్చా?",
    thinking: "ఆలోచిస్తోంది…",
    you: "మీరు",
    end_chat: "చాట్ ముగించు",
    send: "పంపు",
    chat_placeholder: "ప్రశ్న టైప్ చేయండి లేదా మైక్ నొక్కండి…",
    chat_title: "కృషి మిత్రను అడగండి",
    sat_mean: "సగటు",
    sat_share: "వాటా",
    sat_area: "విస్తీర్ణం",
    sat_loading: "తాజా స్పష్టమైన ఉపగ్రహ ఫోటో తెస్తున్నాం…",
    sat_unavailable: "ప్రస్తుతం ఉపగ్రహ ఫోటో లేదు",
    sat_title: "అంతరిక్షం నుండి మీ పొలం",
    actions_title: "ఏం చేయాలి",
    plan_question: "మీ ప్రశ్న (ఐచ్ఛికం)",
    plan_working: "మీ ప్రణాళిక సిద్ధమవుతోంది…",
    plan_rules: "సాధారణ ప్రణాళిక (AI ఆఫ్‌లైన్)",
    plan_ai: "Gemini రాసింది",
    plan_desc: "రాబోయే 7 రోజుల పనులు, మీ వాతావరణం, నేల, ఉపగ్రహ ఫోటో, పంట ఆధారంగా.",
    plan_title: "పొలం కార్యాచరణ ప్రణాళిక",
    cancel: "రద్దు",
    edit: "మార్చు",
    ec_label: "EC (dS/m)",
    ph_label: "pH",
    oc_label: "సేంద్రియ కర్బనం",
    k_label: "పొటాష్ (K)",
    p_label: "భాస్వరం (P)",
    n_label: "నత్రజని (N)",
    rating_high: "ఎక్కువ",
    rating_medium: "మధ్యస్థం",
    rating_low: "తక్కువ",
    fert_organic_low: "సేంద్రియ కర్బనం తక్కువ:",
    fert_rhizobium: "పప్పుధాన్యం: విత్తే ముందు రైజోబియం కల్చర్‌తో విత్తన శుద్ధి చేయండి.",
    fert_note_test: "మీ నేల పరీక్ష ఆధారంగా.",
    fert_note_baseline: "జిల్లా సగటు నేల విలువల ఆధారంగా. మీ పొలానికి ఖచ్చితమైన మోతాదుకు నేల కార్డు అప్‌లోడ్ చేయండి.",
    fert_dose: "మోతాదు (కి.గ్రా/హె)",
    fert_bags: "బస్తాలు",
    fert_topdress: "పై ఎరువు, విత్తిన 30–45 రోజులకు",
    fert_basal: "విత్తేటప్పుడు",
    fert_total: "మీ పొలానికి మొత్తం",
    fert_crop: "పంట",
    fert_title: "ఎరువుల ప్రణాళిక",
    soil_profile_note: "ముందు మీ నేల పరీక్ష వాడతాం. లేనివి జిల్లా సగటు నుండి.",
    soil_tested_on: "పరీక్ష",
    soil_uncertain: "కార్డుపై స్పష్టంగా లేదు, దయచేసి చూడండి",
    soil_review: "కార్డు నుండి చదివిన విలువలు చూసి, తప్పులు సరిచేసి సేవ్ చేయండి.",
    soil_extracting: "కార్డు చదువుతోంది…",
    soil_save: "నేల పరీక్ష సేవ్ చేయండి",
    soil_manual: "విలువలు నమోదు చేయండి",
    soil_upload_hint: "ఫోటో లేదా PDF సరిపోతుంది. మేము సంఖ్యలు చదువుతాం, సేవ్ చేసే ముందు మీరు చూడండి.",
    soil_source_unknown: "అందుబాటులో లేదు",
    soil_source_district_baseline: "జిల్లా సగటు",
    soil_source_soil_test: "నేల పరీక్ష",
    soil_title: "నేల ఆరోగ్యం & ఎరువు",
    root_zone: "వేర్ల ప్రాంతం",
    top_soil: "పై పొర",
    soil_moisture_label: "నేల తేమ (అంచనా)",
    disease_window: "వ్యాధి ప్రమాదం",
    loading: "లోడ్ అవుతోంది…",
    expert_review_link: "నిపుణుల సమీక్ష",
    feat_voice: "5 భాషల్లో వాయిస్",
    feat_doctor: "ఫోటో ఆధారిత మొక్కల వైద్యుడు",
    feat_soil: "నేల కార్డు రీడర్ & ఎరువుల ప్రణాళిక",
    feat_crops: "కారణాలతో పంట సిఫార్సులు",
    feat_weather: "7 రోజుల సూచన & పొలం పనుల సలహా",
    home_no_crops: "ఈ సీజన్‌లో మీ నీరు, నేలకు ఏ పంటా సరిపోదు.",
    home_now: "ఇప్పుడు",
    home_view_all: "అన్నీ చూడండి",
    home_top_crops: "ఈ సీజన్‌కు ఉత్తమ పంటలు",
    home_delete_confirm: "ఈ పొలాన్ని తొలగించాలా? తిరిగి పొందలేరు.",
    home_delete: "తొలగించు",
    home_new_farm: "కొత్త పొలం",
    home_add_farm: "మీ పొలం జోడించండి",
    home_no_farm_desc: "పిన్ కోడ్ లేదా GPS తో పొలం జోడించండి. వారం వాతావరణం, పొలంలో ఏం చేయాలి, ఏ పంటలు సరిపోతాయో తెలుస్తుంది.",
    home_no_farm_title: "మీ సొంత పొలానికి వాతావరణం, పంట సలహా",
    home_today: "ఈరోజు మీ పొలంలో",
    temperature_window: "వేడి, చలి",
    farm_forecast_title: "రోజువారీగా",
    col_day: "రోజు",
    col_rain: "వర్షం",
    col_chance: "అవకాశం",
    col_temp: "గరిష్ఠ / కనిష్ఠ",
    col_wind: "గాలి",
    col_humidity: "తేమ",
    day_forecast_for: "{day} వాతావరణ అంచనా",
    day_back_today: "← ఈరోజు",
    day_tap_hint: "ఆ రోజు వాతావరణం చూడటానికి రోజుపై నొక్కండి",
    rain_jar_scale: "నిండిన పాత్ర = 25 మి.మీ. లేదా ఎక్కువ వర్షం",
    col_gusts: "గాలి విసురు",
    col_et0: "పంట నీటి వినియోగం (ET₀)",
    col_spray: "పిచికారీ",
    water_balance: "వర్షం vs పంట అవసరం",
    past_7d_rain: "గత 7 రోజుల వర్షం",
    weather_updated: "నవీకరించబడింది",
    weather_source_note: "Open-Meteo నుండి మీ ప్రదేశం సూచన. ప్రతి 3 గంటలకు తానే నవీకరణ అవుతుంది.",
    planning_season: "ప్రణాళిక సీజన్",
    current_season_tag: "ప్రస్తుత",
    scene_pending: "చిత్ర తేదీ అందుబాటులో లేదు",
    forecast_pending: "సూచన తెస్తోంది…",
    st_ready: "సిద్ధం",
    st_marginal: "పరిమితం",
    st_wait: "ఆగండి",
    st_safe: "సురక్షితం",
    st_caution: "జాగ్రత్త",
    st_avoid: "వద్దు",
    st_not_needed: "అవసరం లేదు",
    st_monitor: "గమనించండి",
    st_irrigate: "నీరు పెట్టండి",
    st_conserve: "తేమ కాపాడండి",
    st_low: "తక్కువ",
    st_moderate: "మితం",
    st_high: "ఎక్కువ",
    st_normal: "సాధారణం",
    st_cold: "చలి",
    st_unknown: "డేటా లేదు",
    brand_title: "KISANAI",
    brand_sub: "వాతావరణం & పంట సలహా",
    start: "మీ పొలం జోడించండి",
    advice: "పొలం ప్రణాళిక",
    weather: "వాతావరణం",
    crops: "పంట సలహా",
    diagnose: "పంట డాక్టర్",
    expert: "నిపుణుల సమీక్ష",
    live: "తాజా సమాచారం",
    farm: "మీ పొలం",
    save: "సేవ్ చేసి వాతావరణం చూడండి",
    refresh: "రిఫ్రెష్",
    generate: "నా ప్రణాళిక తయారు చేయండి",
    upload_photo: "ఈ ఫోటో చూడండి",
    soil_upload: "నేల ఆరోగ్య కార్డు అప్‌లోడ్ చేయండి",
    uncertain: "అనిశ్చితం",
    listen: "వినండి",
    record: "మాట్లాడండి",
    stop: "ఆపండి",
    accept: "చేస్తాను",
    decline: "వదిలేయండి",
    select_lang_title: "మీ భాషను ఎంచుకోండి",
    select_lang_sub: "సలహా చదవడానికి, వినడానికి భాష ఎంచుకోండి.",
    change_lang: "భాష మార్చండి",
    wind_speed: "గాలి వేగం",
    humidity: "గాలిలో తేమ",
    rainfall_today: "నేటి వర్షపాతం",
    forecast_7d: "7 రోజుల మొత్తం వర్షపాతం",
    soil_status: "భూమి తేమ స్థితి",
    normal_weather: "వాతావరణ హెచ్చరికలు లేవు",
    normal_weather_desc: "IMD ప్రస్తుతం మీ జిల్లాకు తీవ్ర హెచ్చరిక ఇవ్వలేదు.",
    state_label: "రాష్ట్రం",
    district_label: "జిల్లా",
    village_label: "గ్రామం / మండలం (ఐచ్ఛికం)",
    district_placeholder: "జిల్లా లేదా పిన్ కోడ్ నమోదు చేయండి",
    village_placeholder: "గ్రామం లేదా మండలం నమోదు చేయండి",
    current_crop_label: "ప్రస్తుతం ఉన్న పంట",
    previous_crop_label: "గత సీజన్ పంట (పంట మార్పిడి కోసం)",
    select_crop_empty: "-- ఎంచుకోండి (ఖాళీ పొలం / కొత్త పంట ప్రణాళిక) --",
    select_prev_crop_empty: "-- ఎంచుకోండి (ఏదీ లేదు / బీడు) --",
    custom_crop_opt: "✍️ ఇతర పంట...",
    fallow_opt: "ఏదీ లేదు / బీడు",
    affected_crop_title: "సమస్య ఉన్న పంట (ఐచ్ఛికం)",
    auto_detect_crop_opt: "-- తెలియదు, ఫోటో నుండి గుర్తించండి --",
    growth_stage_label: "పంట పెరుగుదల దశ (ఐచ్ఛికం)",
    auto_detect_stage_opt: "-- తెలియదు --",
    stage_seedling: "మొలక దశ (0-20 రోజులు)",
    stage_vegetative: "శాకీయ పెరుగుదల",
    stage_flowering: "పూత దశ",
    stage_pod_filling: "కాయ / గింజ నిండే దశ",
    stage_maturity: "కోతకు సిద్ధమైన దశ",
    observed_symptoms_title: "గమనించిన లక్షణాలు (ఐచ్ఛికం)",
    select_symptom_opt: "-- జాబితా నుండి లక్షణాన్ని ఎంచుకోండి --",
    additional_notes: "అదనపు వివరాలు (ఐచ్ఛికం)",
    notes_placeholder: "ఉదా. వర్షం తర్వాత ఆకులు పసుపు రంగులోకి మారాయి",
    ndmi_label_short: "ఆకుల్లో నీరు (NDMI)",
    ndvi_label_short: "పంట పచ్చదనం (NDVI)",
    water_stress: "నీటి ఒత్తిడి",
    farm_explainer_title: "మీ పొలం కనుగొనండి",
    farm_explainer_desc: "మీ 6 అంకెల పిన్ కోడ్ టైప్ చేయండి లేదా GPS నొక్కండి. తర్వాత మ్యాప్‌లో పొలం 3 నుండి 5 మూలలు నొక్కండి, విస్తీర్ణం మేము లెక్కిస్తాం.",
    diagnose_explainer_title: "మొక్కల డాక్టర్",
    diagnose_explainer_desc: "జబ్బు ఆకు లేదా పురుగు స్పష్టమైన ఫోటో తీయండి. ఏం కనిపిస్తోందో, కారణం ఏమిటో, ఏం చేయడం సురక్షితమో చెబుతాం. ఖచ్చితంగా తెలియకపోతే నిపుణులు చూస్తారు.",
    tap_photo_prompt: "జబ్బు ఆకు ఫోటో తీయడానికి లేదా ఎంచుకోవడానికి నొక్కండి",
    photo_format_hint: "PNG, JPG లేదా WebP ఫార్మాట్లకు మద్దతు ఉంది",
    visible_findings_title: "ఏం కనిపిస్తోంది",
    plausible_causes_title: "ఏమై ఉండవచ్చు",
    safe_next_steps_title: "తర్వాత ఏం చేయాలి",
    escalated_badge: "👨‍🔬 నిపుణుడికి పంపాం",
    analyzing_leaf: "మీ ఫోటో చూస్తున్నాం…",
    analyzing_leaf_desc: "ఆకుపై మచ్చలు, రంగు మార్పు, పురుగులు చూస్తున్నాం.",
    add_farm_first: "ముందు మీ పొలం జోడించండి",
    add_farm_first_desc: "సలహా మీ పొలానికి సరిపడేలా పొలం జోడించండి.",
    evidence_strip_title: "చివరి నవీకరణ",
    latest_weather_obs: "వాతావరణం",
    soil_profile_title: "నేల",
    sowing_window: "విత్తనం",
    spraying_window: "పిచికారీ",
    irrigation_advisory: "నీటిపారుదల",
    drainage_alert: "నీరు నిలవడం",
    table_status: "స్థితి",
    table_range: "పరిధి",
    crop_rec_sub: "మీ నేల, నీరు, వచ్చే వారం వాతావరణం, గత పంట ఆధారంగా.",
    rec_crops_heading: "మీ పొలానికి మంచి పంటలు",
    unsuitable_crops_heading: "ఇప్పుడు సరిపోవు",
    match_score: "సరిపోలిక",
    evidence_cov: "సమాచారం అందుబాటులో",
    decision_factors: "ఎందుకు",
    data_used: "ఆధారం",
    reasoning: "కారణం",
    remedy: "మీరు ఏం చేయవచ్చు",
    sources_badge: "ఆధారం",
    loading_crop_recs: "మీ పొలానికి సరైన పంటలు చూస్తున్నాం…",
    no_crops_found: "ఈ సీజన్‌లో మీ నీరు, నేలకు ఏ పంటా సరిపోదు.",
    why_unsuitable: "ఎందుకు కాదు:",
    view_factors_btn: "కారణాలు చూడండి",
    hide_factors_btn: "కారణాలు దాచండి",
    view_unsuitable_btn: "సరిపోని పంటలు",
    hide_unsuitable_btn: "దాచండి",
    step_farm: "1. పొలం సరిహద్దు",
    step_weather: "2. స్థానిక వాతావరణం",
    step_soil: "3. నేల ఆరోగ్యం",
    step_crops: "4. పంట సిఫార్సులు",
    step_advice: "5. ప్రణాళిక",
    plant_doctor: "పంట డాక్టర్",
    btn_proceed_weather: "స్థానిక వాతావరణం చూడండి →",
    btn_proceed_soil: "నేల ఆరోగ్య వివరాలు (ఐచ్ఛికం) →",
    btn_skip_soil: "నేల పరీక్ష దాటవేసి పంటలు చూడండి →",
    btn_proceed_crops: "పంట సిఫార్సులు చూడండి →",
    btn_proceed_plan: "కార్యాచరణ ప్రణాళిక చూడండి →",
    btn_proceed_doctor: "పంట డాక్టర్‌ను సంప్రదించండి →",
    btn_back_farm: "← పొలం వివరాలకు వెనుకకు",
    btn_back_weather: "← వాతావరణానికి వెనుకకు",
    btn_back_soil: "← నేల ఆరోగ్యానికి వెనుకకు",
    btn_back_crops: "← పంట సిఫార్సులకు వెనుకకు",
    btn_back_plan: "← ప్రణాళికకు వెనుకకు",
    pincode_label: "పిన్ కోడ్",
    pincode_placeholder: "6 అంకెల పిన్ కోడ్, ఉదా. 445001",
    pincode_btn: "స్థానం కనుగొనండి",
    pincode_searching: "పిన్ కోడ్ శోధిస్తోంది...",
    plot_farm_boundary: "మ్యాప్‌లో మీ పొలం గుర్తించండి",
    plot_helper_tip: "మ్యాప్‌లో పొలం మూలలు నొక్కండి. విస్తీర్ణం ఆటోమేటిక్‌గా వస్తుంది.",
    plot_auto_1ac: "1 ఎకరం పెట్టె",
    plot_auto_2ac: "2.5 ఎకరాల పెట్టె",
    plot_clear: "పాయింట్లు తీసివేయండి"
  },
  "kn-IN": {
    photo_quality: "ಫೋಟೋ",
    quality_good: "ಸ್ಪಷ್ಟ",
    quality_usable: "ಸರಿಯಾಗಿದೆ",
    quality_poor: "ಅಸ್ಪಷ್ಟ, ಮತ್ತೆ ತೆಗೆಯಿರಿ",
    quality_not_crop: "ಬೆಳೆ ಕಾಣಿಸಲಿಲ್ಲ",
    fert_rdf_note: "ಶಿಫಾರಸು ಪ್ರಮಾಣ {rdf}, ನಿಮ್ಮ ಮಣ್ಣಿಗೆ ತಕ್ಕಂತೆ ಕಾಲು ಭಾಗ ಕಡಿಮೆ ಅಥವಾ ಹೆಚ್ಚು",
    fert_organic_advice: "ಹೆಕ್ಟೇರಿಗೆ 5–10 ಟನ್ ಕೊಟ್ಟಿಗೆ ಗೊಬ್ಬರ ಅಥವಾ ಕಾಂಪೋಸ್ಟ್ ಹಾಕಿ, ಬೆಳೆ ಉಳಿಕೆ ಮಣ್ಣಿನ ಮೇಲೆ ಬಿಡಿ.",
    fert_confirm: "ನಿಮ್ಮ ಸ್ಥಳೀಯ KVK ಅಥವಾ ಕೃಷಿ ಅಧಿಕಾರಿಯೊಂದಿಗೆ ಖಚಿತಪಡಿಸಿ. ಮೂಲ:",
    rain_7d_label: "ಮುಂದಿನ 7 ದಿನದ ಮಳೆ",
    avg_max_temp: "ಸರಾಸರಿ ಗರಿಷ್ಠ ತಾಪಮಾನ",
    soil_word: "ಮಣ್ಣು",
    water_word: "ನೀರು",
    prev_crop_word: "ಹಿಂದಿನ ಬೆಳೆ",
    district_main_crops: "{district} ನ ಪ್ರಮುಖ ಬೆಳೆಗಳು",
    water_section: "ಹೊಲಕ್ಕೆ ನೀರು",
    soil_section: "ಮಣ್ಣಿನ ವಿಧ",
    water_rainfed: "🌧️ ಮಳೆ ಮಾತ್ರ",
    water_supplemental: "💧 ಬಾವಿ, ಸ್ವಲ್ಪ ನೀರಾವರಿ",
    water_irrigated: "🚿 ಕಾಲುವೆ ಅಥವಾ ಹನಿ, ಪೂರ್ಣ ನೀರಾವರಿ",
    soil_black: "⬛ ಕಪ್ಪು ಮಣ್ಣು",
    soil_red: "🟫 ಕೆಂಪು ಮಣ್ಣು",
    soil_alluvial: "🟨 ಮೆಕ್ಕಲು ಮಣ್ಣು",
    soil_loam: "🪨 ಗೋಡು ಮಣ್ಣು",
    soil_sandy: "🏜️ ಹಗುರ ಮರಳು",
    sym_yellow: "🟡 ಎಲೆ ಹಳದಿ",
    sym_brown: "🟤 ಕಂದು ಕಲೆ",
    sym_powder: "⚪ ಎಲೆಯ ಮೇಲೆ ಬಿಳಿ ಪುಡಿ",
    sym_borer: "🐛 ಕಾಂಡದಲ್ಲಿ ರಂಧ್ರ, ಹುಳು",
    sym_wilt: "🍂 ಸಸಿ ಬಾಡುವುದು",
    sym_curl: "🔄 ಎಲೆ ಮುದುಡುವುದು",
    selected_word: "ಆಯ್ಕೆ",
    expert_code_prompt: "ತಜ್ಞರ ಪ್ರವೇಶ ಕೋಡ್ ನಮೂದಿಸಿ",
    expert_code_open: "ತಜ್ಞರ ಪರಿಶೀಲನೆ ತೆರೆಯಿರಿ",
    edit_farm: "ನಕ್ಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಹೊಲ",
    save_changes: "ಬದಲಾವಣೆ ಉಳಿಸಿ",
    farm_read_only: "ಈ ಹೊಲವನ್ನು ಬೇರೆ ಫೋನ್‌ನಿಂದ ಸೇರಿಸಲಾಗಿದೆ, ನೋಡಬಹುದು ಆದರೆ ಬದಲಿಸಲಾಗದು.",
    plot_corners: "{n} ಮೂಲೆಗಳು ಗುರುತಾಗಿವೆ. ಸರಿಪಡಿಸಲು ಹಳದಿ ಮೂಲೆ ಎಳೆಯಿರಿ.",
    overlay_opacity: "ಉಪಗ್ರಹ ಪದರ",
    home_your_farms: "ನಿಮ್ಮ ಹೊಲಗಳು",
    home_not_yours: "ಬೇರೆ ಫೋನ್‌ನಿಂದ ಸೇರಿಸಲಾಗಿದೆ",
    nav_home: "ಮುಖಪುಟ",
    nav_farm: "ಹೊಲ",
    nav_weather: "ಹವಾಮಾನ",
    nav_crops: "ಬೆಳೆಗಳು",
    nav_plan: "ಯೋಜನೆ",
    nav_doctor: "ವೈದ್ಯ",
    status_accepted: "✓ ಮಾಡುತ್ತೇನೆ",
    status_declined: "ಬಿಟ್ಟಿದ್ದೇನೆ",
    technical_details: "ತಾಂತ್ರಿಕ ವಿವರ (ತಜ್ಞರಿಗೆ)",
    listen_today: "ಇಂದಿನ ಸಲಹೆ ಕೇಳಿ",
    factor_optimal: "ಉತ್ತಮ",
    factor_compatible: "ಸೂಕ್ತ",
    factor_constrained: "ಮಿತ",
    factor_rejected: "ಸೂಕ್ತವಲ್ಲ",
    expert_answers_title: "ತಜ್ಞರ ಉತ್ತರಗಳು",
    uncertainty_title: "ನಮಗೆ ಏಕೆ ಖಚಿತವಿಲ್ಲ",
    next_steps: "ಮುಂದಿನ ಹೆಜ್ಜೆಗಳು",
    causes: "ಸಂಭವನೀಯ ಕಾರಣಗಳು",
    findings: "ಫೋಟೋದಲ್ಲಿ ಕಂಡದ್ದು",
    expert_waiting: "ಕಾಯುತ್ತಿದೆ",
    expert_answered: "ಉತ್ತರಿಸಲಾಗಿದೆ",
    expert_submit: "ಸಲಹೆ ಕಳುಹಿಸಿ",
    expert_reply: "ರೈತರಿಗೆ ಸಲಹೆ",
    expert_none: "ಪರಿಶೀಲನೆಗೆ ಪ್ರಕರಣಗಳಿಲ್ಲ.",
    expert_desc: "ಸಸ್ಯ ಡಾಕ್ಟರ್‌ಗೆ ಖಚಿತವಿಲ್ಲದ ಫೋಟೋಗಳು. ನೋಡಿ ರೈತರಿಗೆ ಉತ್ತರಿಸಿ.",
    expert_title: "ತಜ್ಞರ ಪರಿಶೀಲನೆ",
    chat_privacy: "5 ನಿಮಿಷ ಬಳಸದಿದ್ದರೆ ಚಾಟ್ ಅಳಿಸಲಾಗುತ್ತದೆ.",
    chat_q3: "ಈಗ ಯಾವ ಬೆಳೆ ಬಿತ್ತಬೇಕು?",
    chat_q2: "ಮುಂದಿನ ನೀರು ಯಾವಾಗ ಕೊಡಬೇಕು?",
    chat_q1: "ನಾನು ನಾಳೆ ಸಿಂಪಡಿಸಬಹುದೇ?",
    thinking: "ಯೋಚಿಸುತ್ತಿದೆ…",
    you: "ನೀವು",
    end_chat: "ಚಾಟ್ ಮುಗಿಸಿ",
    send: "ಕಳುಹಿಸಿ",
    chat_placeholder: "ಪ್ರಶ್ನೆ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮೈಕ್ ಒತ್ತಿ…",
    chat_title: "ಕೃಷಿ ಮಿತ್ರನನ್ನು ಕೇಳಿ",
    sat_mean: "ಸರಾಸರಿ",
    sat_share: "ಪಾಲು",
    sat_area: "ವಿಸ್ತೀರ್ಣ",
    sat_loading: "ಇತ್ತೀಚಿನ ಸ್ಪಷ್ಟ ಉಪಗ್ರಹ ಫೋಟೋ ತರುತ್ತಿದ್ದೇವೆ…",
    sat_unavailable: "ಸದ್ಯ ಉಪಗ್ರಹ ಫೋಟೋ ಇಲ್ಲ",
    sat_title: "ಆಕಾಶದಿಂದ ನಿಮ್ಮ ಹೊಲ",
    actions_title: "ಏನು ಮಾಡಬೇಕು",
    plan_question: "ನಿಮ್ಮ ಪ್ರಶ್ನೆ (ಐಚ್ಛಿಕ)",
    plan_working: "ನಿಮ್ಮ ಯೋಜನೆ ಸಿದ್ಧವಾಗುತ್ತಿದೆ…",
    plan_rules: "ಸರಳ ಯೋಜನೆ (AI ಆಫ್‌ಲೈನ್)",
    plan_ai: "Gemini ಬರೆದಿದೆ",
    plan_desc: "ಮುಂದಿನ 7 ದಿನಗಳ ಕೆಲಸ, ನಿಮ್ಮ ಹವಾಮಾನ, ಮಣ್ಣು, ಉಪಗ್ರಹ ಫೋಟೋ, ಬೆಳೆ ಆಧರಿಸಿ.",
    plan_title: "ಹೊಲದ ಕ್ರಿಯಾ ಯೋಜನೆ",
    cancel: "ರದ್ದು",
    edit: "ಬದಲಿಸಿ",
    ec_label: "EC (dS/m)",
    ph_label: "pH",
    oc_label: "ಸಾವಯವ ಇಂಗಾಲ",
    k_label: "ಪೊಟ್ಯಾಷ್ (K)",
    p_label: "ರಂಜಕ (P)",
    n_label: "ಸಾರಜನಕ (N)",
    rating_high: "ಹೆಚ್ಚು",
    rating_medium: "ಮಧ್ಯಮ",
    rating_low: "ಕಡಿಮೆ",
    fert_organic_low: "ಸಾವಯವ ಇಂಗಾಲ ಕಡಿಮೆ:",
    fert_rhizobium: "ದ್ವಿದಳ: ಬಿತ್ತುವ ಮೊದಲು ರೈಜೋಬಿಯಂ ಕಲ್ಚರ್‌ನಿಂದ ಬೀಜೋಪಚಾರ ಮಾಡಿ.",
    fert_note_test: "ನಿಮ್ಮ ಮಣ್ಣು ಪರೀಕ್ಷೆ ಆಧಾರಿತ.",
    fert_note_baseline: "ಜಿಲ್ಲಾ ಸರಾಸರಿ ಮಣ್ಣಿನ ಮೌಲ್ಯ ಆಧಾರಿತ. ನಿಖರ ಪ್ರಮಾಣಕ್ಕೆ ಮಣ್ಣಿನ ಕಾರ್ಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    fert_dose: "ಪ್ರಮಾಣ (ಕೆಜಿ/ಹೆ)",
    fert_bags: "ಚೀಲ",
    fert_topdress: "ಮೇಲುಗೊಬ್ಬರ, ಬಿತ್ತನೆಯ 30–45 ದಿನಗಳ ನಂತರ",
    fert_basal: "ಬಿತ್ತನೆ ವೇಳೆ",
    fert_total: "ನಿಮ್ಮ ಹೊಲಕ್ಕೆ ಒಟ್ಟು",
    fert_crop: "ಬೆಳೆ",
    fert_title: "ಗೊಬ್ಬರ ಯೋಜನೆ",
    soil_profile_note: "ಮೊದಲು ನಿಮ್ಮ ಮಣ್ಣು ಪರೀಕ್ಷೆ ಬಳಸುತ್ತೇವೆ. ಇಲ್ಲದ್ದು ಜಿಲ್ಲಾ ಸರಾಸರಿಯಿಂದ.",
    soil_tested_on: "ಪರೀಕ್ಷೆ",
    soil_uncertain: "ಕಾರ್ಡ್‌ನಲ್ಲಿ ಅಸ್ಪಷ್ಟ, ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ",
    soil_review: "ಕಾರ್ಡ್‌ನಿಂದ ಓದಿದ ಮೌಲ್ಯ ಪರಿಶೀಲಿಸಿ, ತಿದ್ದಿ, ನಂತರ ಉಳಿಸಿ.",
    soil_extracting: "ಕಾರ್ಡ್ ಓದುತ್ತಿದೆ…",
    soil_save: "ಮಣ್ಣು ಪರೀಕ್ಷೆ ಉಳಿಸಿ",
    soil_manual: "ಮೌಲ್ಯ ನಮೂದಿಸಿ",
    soil_upload_hint: "ಫೋಟೋ ಅಥವಾ PDF ಸಾಕು. ನಾವು ಅಂಕೆ ಓದುತ್ತೇವೆ, ಉಳಿಸುವ ಮೊದಲು ನೀವು ನೋಡಿ.",
    soil_source_unknown: "ಲಭ್ಯವಿಲ್ಲ",
    soil_source_district_baseline: "ಜಿಲ್ಲಾ ಸರಾಸರಿ",
    soil_source_soil_test: "ಮಣ್ಣು ಪರೀಕ್ಷೆ",
    soil_title: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ & ಗೊಬ್ಬರ",
    root_zone: "ಬೇರು ವಲಯ",
    top_soil: "ಮೇಲ್ಪದರ",
    soil_moisture_label: "ಮಣ್ಣಿನ ತೇವ (ಅಂದಾಜು)",
    disease_window: "ರೋಗದ ಅಪಾಯ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    expert_review_link: "ತಜ್ಞರ ಪರಿಶೀಲನೆ",
    feat_voice: "5 ಭಾಷೆಗಳಲ್ಲಿ ಧ್ವನಿ",
    feat_doctor: "ಫೋಟೋ ಆಧಾರಿತ ಸಸ್ಯ ವೈದ್ಯ",
    feat_soil: "ಮಣ್ಣಿನ ಕಾರ್ಡ್ ಓದುವಿಕೆ & ಗೊಬ್ಬರ ಯೋಜನೆ",
    feat_crops: "ಕಾರಣಗಳೊಂದಿಗೆ ಬೆಳೆ ಶಿಫಾರಸು",
    feat_weather: "7 ದಿನಗಳ ಮುನ್ಸೂಚನೆ & ಹೊಲದ ಕೆಲಸ ಸಲಹೆ",
    home_no_crops: "ಈ ಹಂಗಾಮಿನಲ್ಲಿ ನಿಮ್ಮ ನೀರು, ಮಣ್ಣಿಗೆ ಯಾವ ಬೆಳೆಯೂ ಹೊಂದುವುದಿಲ್ಲ.",
    home_now: "ಈಗ",
    home_view_all: "ಎಲ್ಲಾ ನೋಡಿ",
    home_top_crops: "ಈ ಹಂಗಾಮಿನ ಉತ್ತಮ ಬೆಳೆಗಳು",
    home_delete_confirm: "ಈ ಹೊಲ ಅಳಿಸಬೇಕೇ? ಹಿಂಪಡೆಯಲಾಗದು.",
    home_delete: "ಅಳಿಸಿ",
    home_new_farm: "ಹೊಸ ಹೊಲ",
    home_add_farm: "ನಿಮ್ಮ ಹೊಲ ಸೇರಿಸಿ",
    home_no_farm_desc: "ಪಿನ್ ಕೋಡ್ ಅಥವಾ GPS ಮೂಲಕ ಹೊಲ ಸೇರಿಸಿ. ವಾರದ ಹವಾಮಾನ, ಹೊಲದಲ್ಲಿ ಏನು ಮಾಡಬೇಕು, ಯಾವ ಬೆಳೆ ಸೂಕ್ತ ಎಂದು ತಿಳಿಯುತ್ತದೆ.",
    home_no_farm_title: "ನಿಮ್ಮ ಸ್ವಂತ ಹೊಲಕ್ಕೆ ಹವಾಮಾನ, ಬೆಳೆ ಸಲಹೆ",
    home_today: "ಇಂದು ನಿಮ್ಮ ಹೊಲದಲ್ಲಿ",
    temperature_window: "ಬಿಸಿ, ಚಳಿ",
    farm_forecast_title: "ದಿನವಾರು",
    col_day: "ದಿನ",
    col_rain: "ಮಳೆ",
    col_chance: "ಸಾಧ್ಯತೆ",
    col_temp: "ಗರಿಷ್ಠ / ಕನಿಷ್ಠ",
    col_wind: "ಗಾಳಿ",
    col_humidity: "ಆರ್ದ್ರತೆ",
    day_forecast_for: "{day} ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    day_back_today: "← ಇಂದು",
    day_tap_hint: "ಆ ದಿನದ ಹವಾಮಾನ ನೋಡಲು ದಿನದ ಮೇಲೆ ಒತ್ತಿ",
    rain_jar_scale: "ತುಂಬಿದ ಪಾತ್ರೆ = 25 ಮಿ.ಮೀ. ಅಥವಾ ಹೆಚ್ಚು ಮಳೆ",
    col_gusts: "ಗಾಳಿ ರಭಸ",
    col_et0: "ಬೆಳೆ ನೀರು ಬಳಕೆ (ET₀)",
    col_spray: "ಸಿಂಪಡಣೆ",
    water_balance: "ಮಳೆ vs ಬೆಳೆಯ ಅಗತ್ಯ",
    past_7d_rain: "ಹಿಂದಿನ 7 ದಿನಗಳ ಮಳೆ",
    weather_updated: "ನವೀಕರಿಸಲಾಗಿದೆ",
    weather_source_note: "Open-Meteo ಯಿಂದ ನಿಮ್ಮ ಜಾಗದ ಮುನ್ಸೂಚನೆ. ಪ್ರತಿ 3 ಗಂಟೆಗೆ ತಾನಾಗಿ ನವೀಕರಣ.",
    planning_season: "ಯೋಜನಾ ಹಂಗಾಮು",
    current_season_tag: "ಪ್ರಸ್ತುತ",
    scene_pending: "ಚಿತ್ರದ ದಿನಾಂಕ ಲಭ್ಯವಿಲ್ಲ",
    forecast_pending: "ಮುನ್ಸೂಚನೆ ತರುತ್ತಿದೆ…",
    st_ready: "ಸಿದ್ಧ",
    st_marginal: "ಮಿತ",
    st_wait: "ಕಾಯಿರಿ",
    st_safe: "ಸುರಕ್ಷಿತ",
    st_caution: "ಎಚ್ಚರಿಕೆ",
    st_avoid: "ಬೇಡ",
    st_not_needed: "ಅಗತ್ಯವಿಲ್ಲ",
    st_monitor: "ಗಮನಿಸಿ",
    st_irrigate: "ನೀರು ಕೊಡಿ",
    st_conserve: "ತೇವ ಉಳಿಸಿ",
    st_low: "ಕಡಿಮೆ",
    st_moderate: "ಮಧ್ಯಮ",
    st_high: "ಹೆಚ್ಚು",
    st_normal: "ಸಾಮಾನ್ಯ",
    st_cold: "ಚಳಿ",
    st_unknown: "ಮಾಹಿತಿ ಇಲ್ಲ",
    brand_title: "KISANAI",
    brand_sub: "ಹವಾಮಾನ & ಬೆಳೆ ಸಲಹೆ",
    start: "ನಿಮ್ಮ ಹೊಲ ಸೇರಿಸಿ",
    advice: "ಹೊಲದ ಯೋಜನೆ",
    weather: "ಹವಾಮಾನ",
    crops: "ಬೆಳೆ ಸಲಹೆ",
    diagnose: "ಬೆಳೆ ವೈದ್ಯ",
    expert: "ತಜ್ಞರ ಪರಿಶೀಲನೆ",
    live: "ಹೊಸ ಮಾಹಿತಿ",
    farm: "ನಿಮ್ಮ ಹೊಲ",
    save: "ಉಳಿಸಿ ಮತ್ತು ಹವಾಮಾನ ನೋಡಿ",
    refresh: "ರಿಫ್ರೆಶ್",
    generate: "ನನ್ನ ಯೋಜನೆ ಮಾಡಿ",
    upload_photo: "ಈ ಫೋಟೋ ಪರಿಶೀಲಿಸಿ",
    soil_upload: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    uncertain: "ಅನಿಶ್ಚಿತ",
    listen: "ಕೇಳಿ",
    record: "ಮಾತನಾಡಿ",
    stop: "ನಿಲ್ಲಿಸಿ",
    accept: "ಮಾಡುತ್ತೇನೆ",
    decline: "ಬಿಡಿ",
    select_lang_title: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    select_lang_sub: "ಸಲಹೆ ಓದಲು ಮತ್ತು ಕೇಳಲು ಭಾಷೆ ಆರಿಸಿ.",
    change_lang: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
    wind_speed: "ಗಾಳಿಯ ವೇಗ",
    humidity: "ಸಾಮಾನ್ಯ ಆರ್ದ್ರತೆ",
    rainfall_today: "ಇಂದಿನ ಮಳೆ",
    forecast_7d: "7 ದಿನಗಳ ಒಟ್ಟು ಮಳೆ",
    soil_status: "ಮಣ್ಣಿನ ತೇವಾಂಶ",
    normal_weather: "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ ಇಲ್ಲ",
    normal_weather_desc: "IMD ಸದ್ಯ ನಿಮ್ಮ ಜಿಲ್ಲೆಗೆ ಗಂಭೀರ ಎಚ್ಚರಿಕೆ ನೀಡಿಲ್ಲ.",
    state_label: "ರಾಜ್ಯ",
    district_label: "ಜಿಲ್ಲೆ",
    village_label: "ಗ್ರಾಮ / ತಾಲೂಕು (ಐಚ್ಛಿಕ)",
    district_placeholder: "ಜಿಲ್ಲೆ ನಮೂದಿಸಿ ಅಥವಾ ಪಿನ್ ಕೋಡ್ ಬಳಸಿ",
    village_placeholder: "ಗ್ರಾಮ ಅಥವಾ ತಾಲೂಕು ನಮೂದಿಸಿ",
    current_crop_label: "ಪ್ರಸ್ತುತ ಬೆಳೆ",
    previous_crop_label: "ಹಿಂದಿನ ಋತುವಿನ ಬೆಳೆ (ಬೆಳೆ ಸರದಿಗಾಗಿ)",
    select_crop_empty: "-- ಆಯ್ಕೆಮಾಡಿ (ಖಾಲಿ ಹೊಲ / ಹೊಸ ಬೆಳೆ ಯೋಜನೆ) --",
    select_prev_crop_empty: "-- ಆಯ್ಕೆಮಾಡಿ (ಯಾವುದೂ ಇಲ್ಲ / ಬಂಜರು) --",
    custom_crop_opt: "✍️ ಇತರ ಬೆಳೆ...",
    fallow_opt: "ಯಾವುದೂ ಇಲ್ಲ / ಬಂಜರು",
    affected_crop_title: "ಬಾಧಿತ ಬೆಳೆ (ಐಚ್ಛಿಕ)",
    auto_detect_crop_opt: "-- ಗೊತ್ತಿಲ್ಲ, ಫೋಟೋದಿಂದ ಗುರುತಿಸಿ --",
    growth_stage_label: "ಬೆಳೆಯ ಹಂತ (ಐಚ್ಛಿಕ)",
    auto_detect_stage_opt: "-- ಗೊತ್ತಿಲ್ಲ --",
    stage_seedling: "ಸಸಿ ಹಂತ (0-20 ದಿನಗಳು)",
    stage_vegetative: "ಸಸ್ಯಕ ಬೆಳವಣಿಗೆ",
    stage_flowering: "ಹೂಬಿಡುವ ಹಂತ",
    stage_pod_filling: "ಕಾಯಿ / ಧಾನ್ಯ ತುಂಬುವ ಹಂತ",
    stage_maturity: "ಕಟಾವಿನ ಹಂತ",
    observed_symptoms_title: "ಕಂಡುಬಂದ ಲಕ್ಷಣಗಳು (ಐಚ್ಛಿಕ)",
    select_symptom_opt: "-- ಪಟ್ಟಿಯಿಂದ ಲಕ್ಷಣ ಆಯ್ಕೆಮಾಡಿ --",
    additional_notes: "ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ (ಐಚ್ಛಿಕ)",
    notes_placeholder: "ಉದಾ. ಮಳೆಯ ನಂತರ ಎಲೆಗಳು ಹಳದಿಯಾಗಿವೆ",
    ndmi_label_short: "ಎಲೆಗಳಲ್ಲಿ ನೀರು (NDMI)",
    ndvi_label_short: "ಬೆಳೆಯ ಹಸಿರು (NDVI)",
    water_stress: "ನೀರಿನ ಒತ್ತಡ",
    farm_explainer_title: "ನಿಮ್ಮ ಹೊಲ ಹುಡುಕಿ",
    farm_explainer_desc: "ನಿಮ್ಮ 6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ GPS ಒತ್ತಿ. ನಂತರ ನಕ್ಷೆಯಲ್ಲಿ ಹೊಲದ 3 ರಿಂದ 5 ಮೂಲೆ ಒತ್ತಿ, ವಿಸ್ತೀರ್ಣ ನಾವು ಲೆಕ್ಕಹಾಕುತ್ತೇವೆ.",
    diagnose_explainer_title: "ಸಸ್ಯ ಡಾಕ್ಟರ್",
    diagnose_explainer_desc: "ರೋಗದ ಎಲೆ ಅಥವಾ ಕೀಟದ ಸ್ಪಷ್ಟ ಫೋಟೋ ತೆಗೆಯಿರಿ. ಏನು ಕಾಣುತ್ತದೆ, ಕಾರಣ ಏನಿರಬಹುದು, ಏನು ಮಾಡುವುದು ಸುರಕ್ಷಿತ ಎಂದು ಹೇಳುತ್ತೇವೆ. ಖಚಿತವಿಲ್ಲದಿದ್ದರೆ ತಜ್ಞರು ನೋಡುತ್ತಾರೆ.",
    tap_photo_prompt: "ರೋಗದ ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಲು ಅಥವಾ ಆರಿಸಲು ಒತ್ತಿ",
    photo_format_hint: "PNG, JPG ಅಥವಾ WebP ಬೆಂಬಲಿತವಾಗಿದೆ",
    visible_findings_title: "ಏನು ಕಾಣುತ್ತಿದೆ",
    plausible_causes_title: "ಏನಿರಬಹುದು",
    safe_next_steps_title: "ಮುಂದೆ ಏನು ಮಾಡಬೇಕು",
    escalated_badge: "👨‍🔬 ತಜ್ಞರಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ",
    analyzing_leaf: "ನಿಮ್ಮ ಫೋಟೋ ನೋಡುತ್ತಿದ್ದೇವೆ…",
    analyzing_leaf_desc: "ಎಲೆಯ ಮೇಲಿನ ಕಲೆ, ಬಣ್ಣ ಬದಲಾವಣೆ, ಕೀಟ ನೋಡುತ್ತಿದ್ದೇವೆ.",
    add_farm_first: "ಮೊದಲು ನಿಮ್ಮ ಹೊಲ ಸೇರಿಸಿ",
    add_farm_first_desc: "ಸಲಹೆ ನಿಮ್ಮ ಹೊಲಕ್ಕೆ ತಕ್ಕಂತೆ ಇರಲು ಹೊಲ ಸೇರಿಸಿ.",
    evidence_strip_title: "ಕೊನೆಯ ನವೀಕರಣ",
    latest_weather_obs: "ಹವಾಮಾನ",
    soil_profile_title: "ಮಣ್ಣು",
    sowing_window: "ಬಿತ್ತನೆ",
    spraying_window: "ಸಿಂಪಡಣೆ",
    irrigation_advisory: "ನೀರು ಹಾಯಿಸುವುದು",
    drainage_alert: "ನೀರು ನಿಲ್ಲುವುದು",
    table_status: "ಸ್ಥಿತಿ",
    table_range: "ವ್ಯಾಪ್ತಿ",
    crop_rec_sub: "ನಿಮ್ಮ ಮಣ್ಣು, ನೀರು, ಮುಂದಿನ ವಾರದ ಹವಾಮಾನ, ಹಿಂದಿನ ಬೆಳೆ ಆಧರಿಸಿ.",
    rec_crops_heading: "ನಿಮ್ಮ ಹೊಲಕ್ಕೆ ಒಳ್ಳೆಯ ಬೆಳೆಗಳು",
    unsuitable_crops_heading: "ಈಗ ಸೂಕ್ತವಲ್ಲ",
    match_score: "ಹೊಂದಾಣಿಕೆ",
    evidence_cov: "ಮಾಹಿತಿ ಲಭ್ಯ",
    decision_factors: "ಏಕೆ",
    data_used: "ಆಧಾರ",
    reasoning: "ಕಾರಣ",
    remedy: "ನೀವು ಏನು ಮಾಡಬಹುದು",
    sources_badge: "ಆಧಾರ",
    loading_crop_recs: "ನಿಮ್ಮ ಹೊಲಕ್ಕೆ ಸರಿಯಾದ ಬೆಳೆ ನೋಡುತ್ತಿದ್ದೇವೆ…",
    no_crops_found: "ಈ ಹಂಗಾಮಿನಲ್ಲಿ ನಿಮ್ಮ ನೀರು, ಮಣ್ಣಿಗೆ ಯಾವ ಬೆಳೆಯೂ ಹೊಂದುವುದಿಲ್ಲ.",
    why_unsuitable: "ಏಕೆ ಇಲ್ಲ:",
    view_factors_btn: "ಕಾರಣ ನೋಡಿ",
    hide_factors_btn: "ಕಾರಣ ಮರೆಮಾಡಿ",
    view_unsuitable_btn: "ಹೊಂದದ ಬೆಳೆಗಳು",
    hide_unsuitable_btn: "ಮರೆಮಾಡಿ",
    step_farm: "1. ಜಮೀನಿನ ಗಡಿ",
    step_weather: "2. ಸ್ಥಳೀಯ ಹವಾಮಾನ",
    step_soil: "3. ಮಣ್ಣಿನ ಆರೋಗ್ಯ",
    step_crops: "4. ಬೆಳೆ ಶಿಫಾರಸು",
    step_advice: "5. ಕಾರ್ಯ ಯೋಜನೆ",
    plant_doctor: "ಬೆಳೆ ವೈದ್ಯ",
    btn_proceed_weather: "ಸ್ಥಳೀಯ ಹವಾಮಾನ ನೋಡಿ →",
    btn_proceed_soil: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ವಿವರಗಳು (ಐಚ್ಛಿಕ) →",
    btn_skip_soil: "ಮಣ್ಣಿನ ಪರೀಕ್ಷೆ ಬಿಟ್ಟು ಬೆಳೆಗಳನ್ನು ನೋಡಿ →",
    btn_proceed_crops: "ಬೆಳೆ ಶಿಫಾರಸುಗಳನ್ನು ನೋಡಿ →",
    btn_proceed_plan: "ಕಾರ್ಯ ಯೋಜನೆ ನೋಡಿ →",
    btn_proceed_doctor: "ಬೆಳೆ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ →",
    btn_back_farm: "← ಹೊಲದ ವಿವರಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    btn_back_weather: "← ಹವಾಮಾನಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    btn_back_soil: "← ಮಣ್ಣಿನ ಆರೋಗ್ಯಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    btn_back_crops: "← ಬೆಳೆ ಶಿಫಾರಸಿಗೆ ಹಿಂತಿರುಗಿ",
    btn_back_plan: "← ಕಾರ್ಯ ಯೋಜನೆಗೆ ಹಿಂತಿರುಗಿ",
    pincode_label: "ಪಿನ್ ಕೋಡ್",
    pincode_placeholder: "6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್, ಉದಾ. 445001",
    pincode_btn: "ಸ್ಥಳ ಹುಡುಕಿ",
    pincode_searching: "ಪಿನ್ ಕೋಡ್ ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    plot_farm_boundary: "ನಕ್ಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಹೊಲ ಗುರುತಿಸಿ",
    plot_helper_tip: "ನಕ್ಷೆಯಲ್ಲಿ ಹೊಲದ ಮೂಲೆಗಳನ್ನು ಒತ್ತಿ. ವಿಸ್ತೀರ್ಣ ತಾನಾಗಿ ಬರುತ್ತದೆ.",
    plot_auto_1ac: "1 ಎಕರೆ ಬಾಕ್ಸ್",
    plot_auto_2ac: "2.5 ಎಕರೆ ಬಾಕ್ಸ್",
    plot_clear: "ಬಿಂದುಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ"
  }
};

