import { Locale } from "../types";

export const copy: Record<Locale, Record<string, string>> = {
  "en-IN": {
    brand_title: "KISANAI",
    brand_sub: "community intelligence",
    hello: "KISANAI",
    sub: "Hyperlocal weather warnings, satellite vegetation scans, and verified regenerative practices tailored to your soil.",
    start: "Add Farm Profile",
    advice: "Field Action Plan",
    weather: "Local Weather",
    crops: "Crop Recommendations",
    diagnose: "Plant Doctor",
    expert: "Knowledge Bank",
    live: "Live Evidence",
    farm: "Farm Profile & Boundary",
    location: "Auto-Detect GPS",
    save: "Save & Proceed to Weather",
    refresh: "Refresh Live Evidence",
    generate: "Generate Field Plan",
    upload_photo: "Diagnose Plant Photo",
    cases: "Farmer Cases Needing Review",
    soil_upload: "Upload Soil Health Card",
    soil_extract: "Extract Soil Nutrients",
    soil_confirm: "Confirm & Save Soil Test",
    soil_auto: "Use Regional Soil Baseline",
    uncertain: "Uncertain",
    listen: "Listen in Audio",
    record: "Ask in Your Language",
    stop: "Stop Recording",
    accept: "Accept",
    decline: "Decline",
    completed: "Completed",
    try_sample: "Load Sample Bundle",
    export_bundle: "Export Practice Bundle",
    practice_library: "Verified Practices",
    exchange: "Sovereign Exchange",
    draft_practice: "Draft New Practice",
    select_lang_title: "Choose Your Language",
    select_lang_sub: "Select your preferred language for advice, weather alerts, and voice guidance.",
    change_lang: "Language",
    wind_speed: "Wind Speed",
    humidity: "Relative Humidity",
    rainfall_today: "Rainfall Today",
    forecast_7d: "7-Day Rain Total",
    soil_status: "Soil Moisture",
    normal_weather: "Normal Weather Conditions",
    normal_weather_desc: "No severe IMD warnings active for this district. Safe for field spraying, weeding, and cultural operations.",
    coordinates: "Field Coordinates",
    gps_detect_prompt: "Coordinates: Tap GPS or enter PIN code",
    syncing: "Detecting GPS...",
    detected_location: "Location Synced",
    state_label: "State",
    district_label: "District",
    village_label: "Village / Taluka (Optional)",
    district_placeholder: "Enter district or use PIN code",
    village_placeholder: "Enter village or taluka",
    current_crop_label: "Current Standing Crop",
    previous_crop_label: "Previous Season Crop (For Rotation Planning)",
    select_crop_empty: "-- Select (None / Planning New Crop) --",
    select_prev_crop_empty: "-- Select (None / Fallow) --",
    custom_crop_opt: "✍️ Other / Custom Crop...",
    fallow_opt: "None / Fallow",
    affected_crop_title: "Affected Crop (Optional)",
    auto_detect_crop_opt: "-- Auto-detect crop from photo (Gemini Vision) --",
    growth_stage_label: "Crop Growth Stage (Optional)",
    auto_detect_stage_opt: "-- Optional: Auto-detect from photo --",
    stage_seedling: "Seedling (0-20 days)",
    stage_vegetative: "Vegetative Growth",
    stage_flowering: "Flowering / Squaring",
    stage_pod_filling: "Boll / Pod Filling",
    stage_maturity: "Pre-Harvest Maturity",
    observed_symptoms_title: "Observed Symptoms (Optional)",
    select_symptom_opt: "-- Select symptom from list (optional) --",
    additional_notes: "Additional Observations (Optional)",
    notes_placeholder: "e.g. Started after recent heavy rain",
    ndmi_label_short: "Canopy Moisture (NDMI)",
    ndvi_label_short: "Vegetation Vigor (NDVI)",
    water_stress: "Water Stress",
    biomass_status: "Biomass Density",
    status_adequate: "Adequate Moisture",
    farm_explainer_title: "Farm Location & Plot Corner Plotter",
    farm_explainer_desc: "Enter your 6-digit Indian PIN code to locate your district, or tap GPS. Click on the map to plot 3 to 5 field corners to compute exact boundary acreage.",
    advice_explainer_title: "Field Action Plan & Satellite Stratification",
    advice_explainer_desc: "Sentinel-2 biophysical zones and ICAR-calibrated field actions for your confirmed plot boundary.",
    diagnose_explainer_title: "Visual Crop Doctor",
    diagnose_explainer_desc: "Powered by Gemini Multimodal AI. Inspects leaf symptoms, diagnoses likely issues, provides low-risk organic remedies, and escalates uncertain cases to real extension experts.",
    tap_photo_prompt: "Tap to upload or take photo of affected leaf",
    photo_format_hint: "PNG, JPG or WebP supported",
    visible_findings_title: "Visible Leaf Symptoms",
    plausible_causes_title: "Plausible Causes",
    safe_next_steps_title: "Safe Organic Remedies & Next Steps",
    uncertainty_note_title: "Uncertainty Note",
    escalated_badge: "👨‍🔬 Escalated to Agronomist",
    analyzing_leaf: "Analyzing Leaf Pathology...",
    analyzing_leaf_desc: "Inspecting discoloration, pest lesions, and fungal symptoms with Gemini Vision...",
    add_farm_first: "Add a Farm First",
    add_farm_first_desc: "Crop diagnostics link directly to your confirmed field crop and location history.",
    evidence_strip_title: "Observation Timestamps",
    latest_sat_scene: "Latest Sentinel-2 Scene",
    latest_weather_obs: "Live Meteorology",
    soil_profile_title: "Soil Nutrient Profile",
    sowing_window: "Sowing Readiness",
    spraying_window: "Spraying Window",
    irrigation_advisory: "Irrigation Advisory",
    drainage_alert: "Drainage & Runoff Risk",
    table_color: "Color",
    table_zone: "Zone",
    table_status: "Status / Label",
    table_range: "Value Range",
    table_area: "Area (Acres)",
    table_share: "Share (%)",
    table_median: "Median",
    geopard_title: "Classified Field Condition Map",
    field_narrative_title: "Satellite Field Narrative",
    optimal_window: "Optimal Window",
    caution_window: "Caution / Marginal",
    avoid_window: "Avoid / Delay",
    crop_rec_title: "Multi-Factor Crop Recommendation Engine",
    crop_rec_sub: "Dynamic agronomic matching based on soil type, water access, 7-day rainfall forecast, and crop rotation history.",
    rec_crops_heading: "Recommended Crops for Your Field",
    unsuitable_crops_heading: "Unsuitable / High-Risk Crops",
    match_score: "Match Score",
    evidence_cov: "Evidence Coverage",
    decision_factors: "Decision Factors & Scientific Explainability",
    data_used: "Data Used",
    reasoning: "Agronomic Rationale",
    remedy: "Corrective Action / Remedy",
    sources_badge: "Data Sources & Regional Baselines Used",
    loading_crop_recs: "Evaluating agronomic suitability for your field...",
    no_crops_found: "No crops match all constraints for this season and water access.",
    why_unsuitable: "Why this crop is not recommended:",
    view_factors_btn: "View Decision Factors Breakdown",
    hide_factors_btn: "Hide Factors Breakdown",
    view_unsuitable_btn: "View Ineligible / High-Risk Crops",
    hide_unsuitable_btn: "Hide Ineligible Crops",
    practices_recommended: "Recommended Regenerative Practices",
    step_farm: "1. Field Plot",
    step_weather: "2. Local Weather",
    step_soil: "3. Soil Health",
    step_crops: "4. Crop Recs",
    step_advice: "5. Field Plan",
    plant_doctor: "Plant Doctor",
    btn_proceed_weather: "Proceed to Local Weather →",
    btn_proceed_soil: "Proceed to Soil Health (Optional) →",
    btn_skip_soil: "Skip Soil Test & See Crops →",
    btn_proceed_crops: "Proceed to Crop Recommendations →",
    btn_proceed_plan: "Proceed to Field Action Plan →",
    btn_proceed_doctor: "Proceed to Crop Doctor →",
    btn_back_farm: "← Back to Field Plot",
    btn_back_weather: "← Back to Local Weather",
    btn_back_soil: "← Back to Soil Health",
    btn_back_crops: "← Back to Crop Recs",
    btn_back_plan: "← Back to Field Plan",
    pincode_label: "PIN Code Search",
    pincode_placeholder: "Enter 6-digit Indian PIN (e.g. 431203, 411001)",
    pincode_btn: "Find Location",
    pincode_searching: "Searching PIN...",
    plot_farm_boundary: "Interactive Farm Boundary Plotter",
    plot_helper_tip: "Click on the map to plot 3 to 5 field corners. Acreage is calculated automatically.",
    plot_auto_1ac: "1-Acre Box",
    plot_auto_2ac: "2.5-Acre Box",
    plot_clear: "Clear Points"
  },
  "hi-IN": {
    brand_title: "KISANAI",
    brand_sub: "सामुदायिक बुद्धिमत्ता",
    hello: "KISANAI",
    sub: "स्थानीय मौसम चेतावनियाँ, उपग्रह फसल स्थिति और आपकी मिट्टी के अनुकूल प्राकृतिक खेती की विधियाँ।",
    start: "खेत प्रोफ़ाइल जोड़ें",
    advice: "खेत कार्य योजना",
    weather: "स्थानीय मौसम",
    crops: "फसल अनुशंसाएँ",
    diagnose: "फसल डॉक्टर",
    expert: "ज्ञान बैंक",
    live: "लाइव प्रमाण",
    farm: "खेत प्रोफ़ाइल एवं सीमा",
    location: "जीपीएस से स्थान लें",
    save: "सहेजें और मौसम देखें",
    refresh: "प्रमाण अपडेट करें",
    generate: "फसल योजना बनाएँ",
    upload_photo: "फसल फोटो जाँचें",
    cases: "समीक्षा हेतु मामले",
    soil_upload: "मृदा कार्ड अपलोड करें",
    soil_extract: "डेटा निकालें",
    soil_confirm: "पुष्टि करें और सहेजें",
    soil_auto: "क्षेत्रीय मृदा आधार चुनें",
    uncertain: "अनिश्चित",
    listen: "ऑडियो में सुनें",
    record: "अपनी भाषा में बोलें",
    stop: "रिकॉर्डिंग रोकें",
    accept: "स्वीकारें",
    decline: "अस्वीकारें",
    completed: "पूर्ण हुआ",
    try_sample: "नमूना बंडल लोड करें",
    export_bundle: "ज्ञान बंडल निर्यात करें",
    practice_library: "सत्यापित विधियाँ",
    exchange: "साझा ज्ञान केंद्र",
    draft_practice: "नई विधि लिखें",
    select_lang_title: "अपनी भाषा चुनें",
    select_lang_sub: "सटीक सलाह, मौसम चेतावनियों एवं आवाज़ के लिए अपनी पसंदीदा भाषा चुनें।",
    change_lang: "भाषा बदलें",
    wind_speed: "हवा की गति",
    humidity: "सापेक्ष आर्द्रता",
    rainfall_today: "आज की वर्षा",
    forecast_7d: "7-दिवसीय कुल वर्षा",
    soil_status: "मृदा नमी स्थिति",
    normal_weather: "सामान्य मौसम स्थिति",
    normal_weather_desc: "जिले में कोई गंभीर मौसम चेतावनी सक्रिय नहीं है। छिड़काव एवं निराई कार्य सुरक्षित हैं।",
    coordinates: "खेत निर्देशांक",
    gps_detect_prompt: "खेत स्थान: पिन कोड दर्ज करें या जीपीएस दबाएँ",
    syncing: "स्थान खोज रहे हैं...",
    detected_location: "स्थान दर्ज हुआ",
    state_label: "राज्य",
    district_label: "जिला",
    village_label: "गाँव / तालुका (वैकल्पिक)",
    district_placeholder: "जिला दर्ज करें या पिन कोड डालें",
    village_placeholder: "गाँव अथवा तालुका दर्ज करें",
    current_crop_label: "खेत में लगी वर्तमान फसल",
    previous_crop_label: "पिछले मौसम की फसल (फसल चक्र हेतु)",
    select_crop_empty: "-- चुनें (खाली खेत / नई फसल योजना) --",
    select_prev_crop_empty: "-- चुनें (कोई नहीं / परती) --",
    custom_crop_opt: "✍️ अन्य / अलग फसल...",
    fallow_opt: "कोई नहीं / परती",
    affected_crop_title: "प्रभावित फसल (वैकल्पिक)",
    auto_detect_crop_opt: "-- फोटो से फसल पहचानें (जेमिनी विजन) --",
    growth_stage_label: "फसल विकास अवस्था (वैकल्पिक)",
    auto_detect_stage_opt: "-- फोटो से विकास अवस्था पहचानें --",
    stage_seedling: "अंकुरण / पौधा (0-20 दिन)",
    stage_vegetative: "वानस्पतिक वृद्धि",
    stage_flowering: "फूल / कली आना",
    stage_pod_filling: "फल / फली / गूलर भरना",
    stage_maturity: "परिपक्वता / कटाई पूर्व",
    observed_symptoms_title: "देखे गए लक्षण (वैकल्पिक)",
    select_symptom_opt: "-- सूची से लक्षण चुनें (वैकल्पिक) --",
    additional_notes: "अतिरिक्त विवरण (वैकल्पिक)",
    notes_placeholder: "उदा. हालिया भारी बारिश के बाद शुरू हुआ",
    ndmi_label_short: "पत्तियों में नमी (NDMI)",
    ndvi_label_short: "फसल वृद्धि और घनत्व (NDVI)",
    water_stress: "जल तनाव",
    biomass_status: "बायोमास स्थिति",
    status_adequate: "पर्याप्त नमी",
    farm_explainer_title: "सटीक खेत स्थान और सीमाएं",
    farm_explainer_desc: "स्थान स्वतः प्राप्त करने के लिए 6-अंकीय पिन कोड दर्ज करें या GPS दबाएँ। खेत के 3 से 5 कोने मानचित्र पर चिह्नित करें।",
    advice_explainer_title: "खेत कार्य योजना एवं उपग्रह विश्लेषण",
    advice_explainer_desc: "सेंटीनेल-2 उपग्रह स्कैन और जेमिनी द्वारा प्रमाणित कृषि कार्य योजना।",
    diagnose_explainer_title: "डिजिटल फसल डॉक्टर",
    diagnose_explainer_desc: "जेमिनी विजन एआई द्वारा संचालित। पत्तियों के लक्षणों की जांच, जैविक उपचार और विशेषज्ञ परामर्श।",
    tap_photo_prompt: "प्रभावित पत्ती का फोटो लें या अपलोड करें",
    photo_format_hint: "PNG, JPG या WebP समर्थित",
    visible_findings_title: "पत्तियों पर दिखे लक्षण",
    plausible_causes_title: "संभावित कारण",
    safe_next_steps_title: "सुरक्षित जैविक उपाय व अगले कदम",
    uncertainty_note_title: "अनिश्चितता सूचना",
    escalated_badge: "👨‍🔬 कृषि विशेषज्ञ को भेजा गया",
    analyzing_leaf: "पत्ती रोग विश्लेषण जारी...",
    analyzing_leaf_desc: "जेमिनी विजन से कीट, फफूंद और पोषक तत्वों की कमी की जांच की जा रही है...",
    add_farm_first: "पहले खेत का विवरण जोड़ें",
    add_farm_first_desc: "फसल निदान सीधे आपके खेत और फसल इतिहास से जुड़ता है।",
    evidence_strip_title: "अवलोकन एवं साक्ष्य समय-मुद्राएं",
    latest_sat_scene: "नवीनतम सेंटीनेल-2 दृश्य",
    latest_weather_obs: "प्रत्यक्ष मौसम विज्ञान",
    soil_profile_title: "मृदा पोषक तत्व प्रोफ़ाइल",
    sowing_window: "बुवाई अनुकूलता",
    spraying_window: "छिड़काव अनुकूलता",
    irrigation_advisory: "सिंचाई सलाह",
    drainage_alert: "जल निकासी व भराव जोखिम",
    table_color: "रंग",
    table_zone: "ज़ोन",
    table_status: "फसल स्थिति",
    table_range: "मान सीमा",
    table_area: "क्षेत्रफल (एकड़)",
    table_share: "हिस्सा (%)",
    table_median: "औसत मान",
    geopard_title: "वर्गीकृत खेत स्थिति मानचित्र",
    field_narrative_title: "उपग्रह खेत विवरण",
    optimal_window: "अनुकूल समय",
    caution_window: "सावधानी / मध्यम",
    avoid_window: "टालें / रोकें",
    crop_rec_title: "वैज्ञानिक बहु-कारक फसल अनुशंसा इंजन",
    crop_rec_sub: "मृदा प्रकार, जल उपलब्धता, 7-दिवसीय वर्षा पूर्वानुमान एवं फसल चक्र के आधार पर सटीक अनुशंसा।",
    rec_crops_heading: "आपके खेत हेतु उपयुक्त अनुशंसित फसलें",
    unsuitable_crops_heading: "अनुपयुक्त / उच्च जोखिम वाली फसलें",
    match_score: "अनुकूलता स्कोर",
    evidence_cov: "प्रमाण कवरेज",
    decision_factors: "वैज्ञानिक कारक एवं निर्णय का आधार",
    data_used: "उपयोग किया गया डेटा",
    reasoning: "कृषि-वैज्ञानिक कारण",
    remedy: "सुधारात्मक उपाय / सलाह",
    sources_badge: "उपयोग किए गए डेटा स्रोत व क्षेत्रीय आधार",
    loading_crop_recs: "खेत के लिए उपयुक्त फसलों का मूल्यांकन जारी...",
    no_crops_found: "इस मौसम और जल स्थिति के लिए कोई फसल पूर्ण अनुकूल नहीं मिली।",
    why_unsuitable: "इस फसल की अनुशंसा न करने का कारण:",
    view_factors_btn: "निर्णय कारकों का विवरण देखें",
    hide_factors_btn: "विवरण छिपाएँ",
    view_unsuitable_btn: "अनुपयुक्त फसलें देखें",
    hide_unsuitable_btn: "अनुपयुक्त फसलें छिपाएँ",
    practices_recommended: "अनुशंसित प्राकृतिक कृषि विधियाँ",
    step_farm: "1. खेत सीमा",
    step_weather: "2. स्थानीय मौसम",
    step_soil: "3. मृदा स्वास्थ्य",
    step_crops: "4. फसल अनुशंसा",
    step_advice: "5. कार्य योजना",
    plant_doctor: "पौधा डॉक्टर",
    btn_proceed_weather: "स्थानीय मौसम देखें →",
    btn_proceed_soil: "मृदा स्वास्थ्य देखें (वैकल्पिक) →",
    btn_skip_soil: "मृदा जांच छोड़ें और फसलें देखें →",
    btn_proceed_crops: "फसल अनुशंसाएँ देखें →",
    btn_proceed_plan: "खेत कार्य योजना देखें →",
    btn_proceed_doctor: "फसल डॉक्टर पर जाएँ →",
    btn_back_farm: "← खेत सीमा पर वापस",
    btn_back_weather: "← मौसम पर वापस",
    btn_back_soil: "← मृदा स्वास्थ्य पर वापस",
    btn_back_crops: "← फसल अनुशंसा पर वापस",
    btn_back_plan: "← कार्य योजना पर वापस",
    pincode_label: "पिन कोड खोज",
    pincode_placeholder: "6-अंकीय पिन कोड दर्ज करें (उदा. 431203, 411001)",
    pincode_btn: "स्थान खोजें",
    pincode_searching: "पिन कोड खोज जारी...",
    plot_farm_boundary: "खेत सीमा रेखांकन (प्लॉटर)",
    plot_helper_tip: "खेत के 3 से 5 कोने मानचित्र पर क्लिक करके चुनें। रकबा स्वतः निकलेगा।",
    plot_auto_1ac: "1 एकड़ बॉक्स",
    plot_auto_2ac: "2.5 एकड़ बॉक्स",
    plot_clear: "बिंदु हटाएँ"
  },
  "mr-IN": {
    brand_title: "KISANAI",
    brand_sub: "सामुदायिक बुद्धिमत्ता",
    hello: "KISANAI",
    sub: "अचूक हवामान इशारे, उपग्रह पिकांची स्थिती आणि आपल्या जमिनीला अनुकूल नैसर्गिक शेती पद्धती.",
    start: "शेत जोडा",
    advice: "शेत कृती योजना",
    weather: "स्थानिक हवामान",
    crops: "पीक शिफारसी",
    diagnose: "पीक डॉक्टर",
    expert: "ज्ञान भांडार",
    live: "थेट पुरावे",
    farm: "शेत माहिती व सीमा",
    location: "GPS द्वारे स्थान घ्या",
    save: "जतन करा व हवामान पहा",
    refresh: "माहिती अद्ययावत करा",
    generate: "पीक नियोजन करा",
    upload_photo: "पिकाचा फोटो तपासा",
    cases: "तज्ज्ञ पुनरावलोकन",
    soil_upload: "माती परीक्षण कार्ड अपलोड करा",
    soil_extract: "माहिती काढा",
    soil_confirm: "पुष्टी करा आणि जतन करा",
    soil_auto: "स्थानिक माती आधार वापरा",
    uncertain: "अनिश्चित",
    listen: "ऑडिओ ऐका",
    record: "आपल्या भाषेत बोला",
    stop: "रेकॉर्डिंग थांबवा",
    accept: "स्वीकारा",
    decline: "नाकारा",
    completed: "पूर्ण झाले",
    try_sample: "नमुना बंडल लोड करा",
    export_bundle: "ज्ञान बंडल निर्यात करा",
    practice_library: "सत्यापित पद्धती",
    exchange: "ज्ञान देवाणघेवाण",
    draft_practice: "नवीन पद्धत नोंदवा",
    select_lang_title: "आपली भाषा निवडा",
    select_lang_sub: "सल्ला, हवामान इशारे आणि व्हॉइस मार्गदर्शनासाठी आपली भाषा निवडा.",
    change_lang: "भाषा बदला",
    wind_speed: "वाऱ्याचा वेग",
    humidity: "हवेतील आर्द्रता",
    rainfall_today: "आजचा पाऊस",
    forecast_7d: "७ दिवसांचा एकूण पाऊस",
    soil_status: "जमिनीतील ओलावा",
    normal_weather: "सामान्य हवामान स्थिती",
    normal_weather_desc: "जिल्ह्यात कोणताही तीव्र इशारा नाही. फवारणी, खुरपणी आणि मशागत सुरक्षित आहे.",
    coordinates: "शेताचे स्थान (अक्षांश/रेखांश)",
    gps_detect_prompt: "पिन कोड टाका किंवा GPS बटन दाबून स्थान मिळवा",
    syncing: "स्थान शोधत आहे...",
    detected_location: "स्थान निश्चित झाले",
    state_label: "राज्य",
    district_label: "जिल्हा",
    village_label: "गाव / तालुका (ऐच्छिक)",
    district_placeholder: "जिल्हा टाका किंवा पिन कोड वापरा",
    village_placeholder: "गाव किंवा तालुका टाका",
    current_crop_label: "शेतातील सध्याचे पीक",
    previous_crop_label: "मागील हंगामातील पीक (पीक फेरपालट)",
    select_crop_empty: "-- निवडा (काही नाही / नवीन पीक नियोजन) --",
    select_prev_crop_empty: "-- निवडा (काही नाही / पडीक) --",
    custom_crop_opt: "✍️ इतर / वेगळे पीक...",
    fallow_opt: "काही नाही / पडीक",
    affected_crop_title: "बाधित पीक (ऐच्छिक)",
    auto_detect_crop_opt: "-- फोटोवरून पीक ओळखा (जेमिनी व्हिजन) --",
    growth_stage_label: "पिकाची वाढीची अवस्था (ऐच्छिक)",
    auto_detect_stage_opt: "-- फोटोवरून अवस्था ओळखा --",
    stage_seedling: "रोप अवस्था (०-२० दिवस)",
    stage_vegetative: "शाकीय वाढ",
    stage_flowering: "फुलोरा अवस्था",
    stage_pod_filling: "बोंड / शेंगा भरणे",
    stage_maturity: "पक्वता / काढणीपूर्वी",
    observed_symptoms_title: "दिसलेली लक्षणे (ऐच्छिक)",
    select_symptom_opt: "-- यादीतून लक्षण निवडा (ऐच्छिक) --",
    additional_notes: "अधिक निरीक्षणे (ऐच्छिक)",
    notes_placeholder: "उदा. पावसाच्या खंडानंतर लक्षणे दिसली",
    ndmi_label_short: "पानांमधील ओलावा (NDMI)",
    ndvi_label_short: "पिकाची जोमदार वाढ (NDVI)",
    water_stress: "पाण्याचा ताण",
    biomass_status: "बायोमास घनता",
    status_adequate: "पुरेसा ओलावा",
    farm_explainer_title: "अचूक शेती स्थान आणि बांध सीमा",
    farm_explainer_desc: "आपला ६-अंकी पिन कोड टाका किंवा GPS वापरा. शेताचे ३ ते ५ कोपरे नकाशावर क्लिक करून निवडा.",
    advice_explainer_title: "शेत कृती योजना व उपग्रह विश्लेषण",
    advice_explainer_desc: "सेंटिनेल-२ उपग्रह स्कॅन आणि जेमिनी एआय द्वारे स्थानिक नैसर्गिक शेती कृती आराखडा.",
    diagnose_explainer_title: "डिजिटल पीक डॉक्टर",
    diagnose_explainer_desc: "जेमिनी व्हिजन एआय द्वारे पानांच्या लक्षणांची तपासणी, सेंद्रिय उपाय आणि तज्ज्ञ सल्ला.",
    tap_photo_prompt: "बाधित पानाचा फोटो काढा किंवा अपलोड करा",
    photo_format_hint: "PNG, JPG किंवा WebP समर्थित",
    visible_findings_title: "पानांवर दिसलेली लक्षणे",
    plausible_causes_title: "संभाव्य कारणे",
    safe_next_steps_title: "सुरक्षित सेंद्रिय उपाय आणि पुढील पावले",
    uncertainty_note_title: "अनिश्चितता नोंद",
    escalated_badge: "👨‍🔬 कृषितज्ज्ञांकडे पाठवले",
    analyzing_leaf: "पानावरील रोगाचे विश्लेषण सुरू...",
    analyzing_leaf_desc: "जेमिनी व्हिजन द्वारे कीड, बुरशी आणि पोषणाचा ताण तपासला जात आहे...",
    add_farm_first: "प्रथम शेताची माहिती भरा",
    add_farm_first_desc: "पीक रोगनिदान थेट तुमच्या शेतातील पिकाशी जोडलेले असते.",
    evidence_strip_title: "निरीक्षण वेळ",
    latest_sat_scene: "नवीनतम सेंटिनेल-२ उपग्रह दृश्य",
    latest_weather_obs: "थेट हवामान निरीक्षण",
    soil_profile_title: "माती पोषण प्रोफाइल",
    sowing_window: "पेरणी अनुकूलता",
    spraying_window: "फवारणी अनुकूलता",
    irrigation_advisory: "सिंचन सल्ला",
    drainage_alert: "पाणी निचरा व साचण्याचा धोका",
    table_color: "रंग",
    table_zone: "झोन",
    table_status: "पिकाची स्थिती",
    table_range: "मूल्य श्रेणी",
    table_area: "क्षेत्रफळ (एकर)",
    table_share: "वाटा (%)",
    table_median: "मध्यक मान",
    geopard_title: "वर्गीकृत शेत स्थिती नकाशा",
    field_narrative_title: "उपग्रह शेत निरीक्षण",
    optimal_window: "अनुकूल वेळ",
    caution_window: "सावधगिरी / मध्यम",
    avoid_window: "थांबवा / टाळा",
    crop_rec_title: "वैज्ञानिक बहु-घटक पीक शिफारस प्रणाली",
    crop_rec_sub: "मातीचा प्रकार, पाण्याची उपलब्धता, ७-दिवसीय पावसाचा अंदाज आणि पीक फेरपालटीवर आधारित अचूक शिफारस.",
    rec_crops_heading: "तुमच्या शेतासाठी योग्य शिफारस केलेली पिके",
    unsuitable_crops_heading: "अयोग्य / जास्त जोखीम असलेली पिके",
    match_score: "अनुकूलता टक्केवारी",
    evidence_cov: "पुरावा कव्हरेज",
    decision_factors: "निर्णयाचे घटक आणि वैज्ञानिक स्पष्टीकरण",
    data_used: "वापरलेला डेटा",
    reasoning: "कृषी-वैज्ञानिक कारण",
    remedy: "उपाययोजना / सुधारणा",
    sources_badge: "वापरलेले अधिकृत डेटा स्रोत व प्रादेशिक निकष",
    loading_crop_recs: "शेतासाठी योग्य पिकांची तपासणी सुरू आहे...",
    no_crops_found: "या हंगामात आणि उपलब्ध पाण्यात कोणतीही शिफारस जुळली नाही.",
    why_unsuitable: "या पिकाची शिफारस का नाकारली:",
    view_factors_btn: "निर्णय घटकांचे सविस्तर विश्लेषण पहा",
    hide_factors_btn: "विश्लेषण लपवा",
    view_unsuitable_btn: "अयोग्य पिके पहा",
    hide_unsuitable_btn: "अयोग्य पिके लपवा",
    practices_recommended: "शिफारस केलेल्या नैसर्गिक शेती पद्धती",
    step_farm: "१. शेत सीमा",
    step_weather: "२. स्थानिक हवामान",
    step_soil: "३. माती आरोग्य",
    step_crops: "४. पीक शिफारसी",
    step_advice: "५. कृती योजना",
    plant_doctor: "पीक डॉक्टर",
    btn_proceed_weather: "स्थानिक हवामान पहा →",
    btn_proceed_soil: "माती आरोग्य तपासा (ऐच्छिक) →",
    btn_skip_soil: "माती तपासणी वगळा व पिके पहा →",
    btn_proceed_crops: "पीक शिफारसी पहा →",
    btn_proceed_plan: "शेत कृती योजना पहा →",
    btn_proceed_doctor: "पीक डॉक्टरवर जा →",
    btn_back_farm: "← शेत सीमेवर परत",
    btn_back_weather: "← हवामानावर परत",
    btn_back_soil: "← माती आरोग्याकडे परत",
    btn_back_crops: "← पीक शिफारसीवर परत",
    btn_back_plan: "← कृती योजनेवर परत",
    pincode_label: "पिन कोड शोध",
    pincode_placeholder: "६-अंकी पिन कोड टाका (उदा. 431203, 411001)",
    pincode_btn: "स्थान शोधा",
    pincode_searching: "पिन कोड शोधत आहे...",
    plot_farm_boundary: "शेताचे कोपरे व बांध रेखांकन",
    plot_helper_tip: "नकाशावर क्लिक करून शेताचे ३ ते ५ कोपरे निवडा. एकर क्षेत्रफळ आपोआप मोजले जाईल.",
    plot_auto_1ac: "१ एकर बॉक्स",
    plot_auto_2ac: "२.५ एकर बॉक्स",
    plot_clear: "बिंदू हटवा"
  },
  "te-IN": {
    brand_title: "KISANAI",
    brand_sub: "కమ్యూనిటీ ఆధారిత వ్యవసాయం",
    hello: "KISANAI",
    sub: "ఖచ్చితమైన వాతావరణ హెచ్చరికలు, ఉపగ్రహ పంట స్థితి మరియు పునరుత్పాదక సేంద్రియ విధానాలు.",
    start: "పొలం వివరాలు జోడించండి",
    advice: "క్షేత్ర కార్యాచరణ ప్రణాళిక",
    weather: "స్థానిక వాతావరణం",
    crops: "పంట సిఫార్సులు",
    diagnose: "పంట డాక్టర్",
    expert: "జ్ఞాన కేంద్రం",
    live: "ప్రత్యక్ష ఆధారాలు",
    farm: "పొలం సరిహద్దులు",
    location: "GPS స్థానాన్ని వాడండి",
    save: "సేవ్ చేసి వాతావరణం చూడండి",
    refresh: "ఆధారాలు నవీకరించండి",
    generate: "పంట ప్రణాళిక పొందండి",
    upload_photo: "పంట ఫోటోను పరీక్షించండి",
    cases: "సమీక్ష కేసులు",
    soil_upload: "సాయిల్ కార్డ్ అప్‌లోడ్",
    soil_extract: "డేటా సేకరించండి",
    soil_confirm: "నిర్ధారించి సేవ్ చేయండి",
    soil_auto: "ప్రాంతీయ సాయిల్ డేటా",
    uncertain: "అనిశ్చితం",
    listen: "వాయిస్ వినండి",
    record: "మీ భాషలో మాట్లాడండి",
    stop: "ఆపండి",
    accept: "అంగీకరించండి",
    decline: "తిరస్కరించండి",
    completed: "పూర్తయింది",
    try_sample: "నమూనా బండిల్ లోడ్ చేయండి",
    export_bundle: "జ్ఞాన బండిల్ ఎగుమతి",
    practice_library: "ధృవీకరించిన పద్ధతులు",
    exchange: "జ్ఞాన మార్పిడి",
    draft_practice: "కొత్త పద్ధతిని నమోదు చేయండి",
    select_lang_title: "మీ భాషను ఎంచుకోండి",
    select_lang_sub: "ఖచ్చితమైన వ్యవసాయ సలహాలు మరియు వాతావరణ సమాచారం కోసం మీ భాషను ఎంచుకోండి.",
    change_lang: "భాష మార్చండి",
    wind_speed: "గాలి వేగం",
    humidity: "గాలిలో తేమ",
    rainfall_today: "నేటి వర్షపాతం",
    forecast_7d: "7 రోజుల మొత్తం వర్షపాతం",
    soil_status: "భూమి తేమ స్థితి",
    normal_weather: "సాధారణ వాతావరణం",
    normal_weather_desc: "ఈ జిల్లాకు ఎటువంటి ప్రమాదకర హెచ్చరికలు లేవు. పిచికారీ మరియు కలుపుతీత పనులు సురక్షితం.",
    coordinates: "పొలం స్థాన వివరాలు",
    gps_detect_prompt: "పిన్ కోడ్ నమోదు చేయండి లేదా GPS వాడండి",
    syncing: "లొకేషన్ గుర్తించబడుతోంది...",
    detected_location: "లొకేషన్ నమోదయింది",
    state_label: "రాష్ట్రం",
    district_label: "జిల్లా",
    village_label: "గ్రామం / మండలం (ఐచ్ఛికం)",
    district_placeholder: "జిల్లా లేదా పిన్ కోడ్ నమోదు చేయండి",
    village_placeholder: "గ్రామం లేదా మండలం నమోదు చేయండి",
    current_crop_label: "ప్రస్తుతం ఉన్న పంట",
    previous_crop_label: "గత సీజన్ పంట (పంట మార్పిడి కోసం)",
    select_crop_empty: "-- ఎంచుకోండి (ఖాళీ పొలం / కొత్త పంట ప్రణాళిక) --",
    select_prev_crop_empty: "-- ఎంచుకోండి (ఏదీ లేదు / బీడు) --",
    custom_crop_opt: "✍️ ఇతర పంట...",
    fallow_opt: "ఏదీ లేదు / బీడు",
    affected_crop_title: "సమస్య ఉన్న పంట (ఐచ్ఛికం)",
    auto_detect_crop_opt: "-- ఫోటో నుండి పంటను గుర్తించండి (జెమిని) --",
    growth_stage_label: "పంట పెరుగుదల దశ (ఐచ్ఛికం)",
    auto_detect_stage_opt: "-- ఫోటో నుండి దశను గుర్తించండి --",
    stage_seedling: "మొలక దశ (0-20 రోజులు)",
    stage_vegetative: "శాకీయ పెరుగుదల",
    stage_flowering: "పూత దశ",
    stage_pod_filling: "కాయ / గింజ నిండే దశ",
    stage_maturity: "కోతకు సిద్ధమైన దశ",
    observed_symptoms_title: "గమనించిన లక్షణాలు (ఐచ్ఛికం)",
    select_symptom_opt: "-- జాబితా నుండి లక్షణాన్ని ఎంచుకోండి --",
    additional_notes: "అదనపు వివరాలు (ఐచ్ఛికం)",
    notes_placeholder: "ఉదా. వర్షం తర్వాత ఆకులు పసుపు రంగులోకి మారాయి",
    ndmi_label_short: "ఆకులలో తేమ శాతం (NDMI)",
    ndvi_label_short: "పంట పచ్చదనం & ఆరోగ్యం (NDVI)",
    water_stress: "నీటి ఒత్తిడి",
    biomass_status: "బయోమాస్ సాంద్రత",
    status_adequate: "సరిపడా తేమ",
    farm_explainer_title: "ఖచ్చితమైన పొలం సరిహద్దులు",
    farm_explainer_desc: "6 అంకెల పిన్ కోడ్ నమోదు చేయండి లేదా GPS వాడండి. మ్యాప్‌పై క్లిక్ చేసి పొలం సరిహద్దు మూలలను గుర్తించండి.",
    advice_explainer_title: "క్షేత్ర ప్రణాళిక & ఉపగ్రహ విశ్లేషణ",
    advice_explainer_desc: "సెంటినెల్-2 ఉపగ్రహం మరియు జెమిని ఆధారిత వ్యవసాయ ప్రణాళిక.",
    diagnose_explainer_title: "డిజిటల్ పంట డాక్టర్",
    diagnose_explainer_desc: "జెమిని ఏఐ ద్వారా ఆధారితం. ఆకుల లక్షణాలు, సేంద్రీయ నివారణలు మరియు నిపుణుల సలహా.",
    tap_photo_prompt: "బాధిత ఆకు ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి",
    photo_format_hint: "PNG, JPG లేదా WebP ఫార్మాట్లకు మద్దతు ఉంది",
    visible_findings_title: "ఆకులపై కనిపించే లక్షణాలు",
    plausible_causes_title: "సాధ్యమయ్యే కారణాలు",
    safe_next_steps_title: "సురక్షిత సేంద్రీయ నివారణలు & తదుపరి చర్యలు",
    uncertainty_note_title: "అనిశ్చితి గమనిక",
    escalated_badge: "👨‍🔬 వ్యవసాయ నిపుణుడికి పంపబడింది",
    analyzing_leaf: "ఆకు వ్యాధి విశ్లేషణ జరుగుతోంది...",
    analyzing_leaf_desc: "జెమిని విజన్‌తో తెగుళ్ళు మరియు శిలీంధ్రాల లక్షణాలను పరిశీలిస్తోంది...",
    add_farm_first: "ముందుగా పొలం వివరాలు జోడించండి",
    add_farm_first_desc: "పంట నిర్ధారణ నేరుగా మీ పొలం వివరాలతో అనుసంధానించబడి ఉంటుంది.",
    evidence_strip_title: "పరిశీలన సమయం",
    latest_sat_scene: "తాజా సెంటినెల్-2 ఉపగ్రహ చిత్రం",
    latest_weather_obs: "లైవ్ వాతావరణ పరిశీలన",
    soil_profile_title: "నేల పోషకాల వివరాలు",
    sowing_window: "విత్తన అనుకూలత",
    spraying_window: "పిచికారీ అనుకూలత",
    irrigation_advisory: "నీటిపారుదల సలహా",
    drainage_alert: "నీటి నిల్వ ప్రమాదం",
    table_color: "రంగు",
    table_zone: "జోన్",
    table_status: "పంట స్థితి",
    table_range: "విలువ పరిధి",
    table_area: "విస్తీర్ణం (ఎకరాలు)",
    table_share: "వాటా (%)",
    table_median: "మధ్యస్థం",
    geopard_title: "వర్గీకరించిన పొలం స్థితి పటం",
    field_narrative_title: "ఉపగ్రహ పరిశీలనా సారాంశం",
    optimal_window: "అనుకూల సమయం",
    caution_window: "జాగ్రత్త / మధ్యస్థం",
    avoid_window: "ఆపండి / వాయిదా",
    crop_rec_title: "ఖచ్చితమైన బహుళ-కారక పంట సిఫార్సు వ్యవస్థ",
    crop_rec_sub: "నేల రకం, నీటి లభ్యత, 7 రోజుల వర్షపాత సూచన మరియు పంట మార్పిడి ఆధారంగా శాస్త్రీయ సిఫార్సు.",
    rec_crops_heading: "మీ పొలానికి సిఫార్సు చేయబడిన అనుకూల పంటలు",
    unsuitable_crops_heading: "అనుకూలం కాని / అధిక ప్రమాదకర పంటలు",
    match_score: "అనుకూలత స్కోర్",
    evidence_cov: "సాక్ష్యాల కవరేజ్",
    decision_factors: "శాస్త్రీయ నిర్ణయ కారకాలు మరియు వివరణ",
    data_used: "ఉపయోగించిన డేటా",
    reasoning: "వ్యవసాయ శాస్త్రీయ కారణం",
    remedy: "నివారణ చర్య / పరిష్కారం",
    sources_badge: "ఉపయోగించిన అధికారిక డేటా మూలాలు",
    loading_crop_recs: "పొలానికి తగిన పంటల విశ్లేషణ జరుగుతోంది...",
    no_crops_found: "ఈ కాలానికి మరియు నీటి వనరులకు తగిన పంటలు కనుగొనబడలేదు.",
    why_unsuitable: "ఈ పంట ఎందుకు సిఫార్సు చేయబడలేదు:",
    view_factors_btn: "నిర్ణయ కారకాల వివరాలు చూడండి",
    hide_factors_btn: "వివరాలను దాచండి",
    view_unsuitable_btn: "అనుకూలం కాని పంటలను చూడండి",
    hide_unsuitable_btn: "అనుకూలం కాని పంటలను దాచండి",
    practices_recommended: "సిఫార్సు చేయబడిన సేంద్రియ పద్ధతులు",
    step_farm: "1. పొలం సరిహద్దు",
    step_weather: "2. స్థానిక వాతావరణం",
    step_soil: "3. నేల ఆరోగ్యం",
    step_crops: "4. పంట సిఫార్సులు",
    step_advice: "5. ప్రణాళిక",
    plant_doctor: "పంట డాక్టర్",
    btn_proceed_weather: "స్థానిక వాతావరణం చూడండి →",
    btn_proceed_soil: "నేల ఆరోగ్య వివరాలు (ఐచ్ఛికం) →",
    btn_skip_soil: "నేల పరీక్ష దాటవేసి పంటలు చూడండి →",
    btn_proceed_crops: "పంట సిఫార్సులు చూడండి →",
    btn_proceed_plan: "కార్యాచరణ ప్రణాళిక చూడండి →",
    btn_proceed_doctor: "పంట డాక్టర్‌ను సంప్రదించండి →",
    btn_back_farm: "← పొలం వివరాలకు వెనుకకు",
    btn_back_weather: "← వాతావరణానికి వెనుకకు",
    btn_back_soil: "← నేల ఆరోగ్యానికి వెనుకకు",
    btn_back_crops: "← పంట సిఫార్సులకు వెనుకకు",
    btn_back_plan: "← ప్రణాళికకు వెనుకకు",
    pincode_label: "పిన్ కోడ్ శోధన",
    pincode_placeholder: "6 అంకెల పిన్ కోడ్ నమోదు చేయండి (ఉదా. 431203)",
    pincode_btn: "స్థానం కనుగొనండి",
    pincode_searching: "పిన్ కోడ్ శోధిస్తోంది...",
    plot_farm_boundary: "పొలం సరిహద్దుల మ్యాపింగ్",
    plot_helper_tip: "మ్యాప్‌పై క్లిక్ చేసి పొలం 3 నుండి 5 మూలలను గుర్తించండి. విస్తీర్ణం లెక్కించబడుతుంది.",
    plot_auto_1ac: "1 ఎకరం పెట్టె",
    plot_auto_2ac: "2.5 ఎకరాల పెట్టె",
    plot_clear: "పాయింట్లు తీసివేయండి"
  },
  "kn-IN": {
    brand_title: "KISANAI",
    brand_sub: "ಸಮುದಾಯ ಕೃಷಿ ಜ್ಞಾನ",
    hello: "KISANAI",
    sub: "ನಿಖರ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ, ಉಪಗ್ರಹ ಬೆಳೆ ಆರೋಗ್ಯ ಮತ್ತು ನೈಸರ್ಗಿಕ ಕೃಷಿ ಪದ್ಧತಿಗಳು.",
    start: "ಹೊಲದ ವಿವರ ಸೇರಿಸಿ",
    advice: "ಕ್ಷೇತ್ರ ಕಾರ್ಯ ಯೋಜನೆ",
    weather: "ಸ್ಥಳೀಯ ಹವಾಮಾನ",
    crops: "ಬೆಳೆ ಶಿಫಾರಸುಗಳು",
    diagnose: "ಬೆಳೆ ವೈದ್ಯ",
    expert: "ಕೃಷಿ ಜ್ಞಾನ ಬ್ಯಾಂಕ್",
    live: "ನೇರ ಸಾಕ್ಷ್ಯ",
    farm: "ಹೊಲದ ವಿವರ ಮತ್ತು ಗಡಿ",
    location: "GPS ಸ್ಥಳ ಪಡೆಯಿರಿ",
    save: "ಉಳಿಸಿ ಮತ್ತು ಹವಾಮಾನ ನೋಡಿ",
    refresh: "ಸಾಕ್ಷ್ಯ ನವೀಕರಿಸಿ",
    generate: "ಬೆಳೆ ಯೋಜನೆ ರಚಿಸಿ",
    upload_photo: "ಬೆಳೆ ಚಿತ್ರ ಪರೀಕ್ಷಿಸಿ",
    cases: "ಪರಿಶೀಲನಾ ಪ್ರಕರಣಗಳು",
    soil_upload: "ಮಣ್ಣಿನ ಕಾರ್ಡ್ ಅಪ್‌ಲೋಡ್",
    soil_extract: "ಮಾಹಿತಿ ಪಡೆಯಿರಿ",
    soil_confirm: "ಖಚಿತಪಡಿಸಿ ಮತ್ತು ಉಳಿಸಿ",
    soil_auto: "ಪ್ರಾದೇಶಿಕ ಮಣ್ಣಿನ ಮಾಹಿತಿ",
    uncertain: "ಅನಿಶ್ಚಿತ",
    listen: "ಆಡಿಯೋ ಆಲಿಸಿ",
    record: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ",
    stop: "ನಿಲ್ಲಿಸಿ",
    accept: "ಸ್ವೀಕರಿಸಿ",
    decline: "ತಿರಸ್ಕರಿಸಿ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    try_sample: "ಮಾದರಿ ಬಂಡಲ್ ಲೋಡ್ ಮಾಡಿ",
    export_bundle: "ಜ್ಞಾನ ಬಂಡಲ್ ರಫ್ತು",
    practice_library: "ಪರಿಶೀಲಿಸಿದ ವಿಧಾನಗಳು",
    exchange: "ಜ್ಞಾನ ವಿನಿಮಯ",
    draft_practice: "ಹೊಸ ವಿಧಾನ ಬರೆಯಿರಿ",
    select_lang_title: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    select_lang_sub: "ನಿಖರ ಕೃಷಿ ಸಲಹೆಗಳು ಮತ್ತು ಹವಾಮಾನ ಮುನ್ಸೂಚನೆಗಾಗಿ ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    change_lang: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
    wind_speed: "ಗಾಳಿಯ ವೇಗ",
    humidity: "ಸಾಮಾನ್ಯ ಆರ್ದ್ರತೆ",
    rainfall_today: "ಇಂದಿನ ಮಳೆ",
    forecast_7d: "7 ದಿನಗಳ ಒಟ್ಟು ಮಳೆ",
    soil_status: "ಮಣ್ಣಿನ ತೇವಾಂಶ",
    normal_weather: "ಸಾಮಾನ್ಯ ಹವಾಮಾನ",
    normal_weather_desc: "ಜಿಲ್ಲೆಯಲ್ಲಿ ಯಾವುದೇ ತೀವ್ರ ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ. ಔಷಧಿ ಸಿಂಪಡಣೆ ಮತ್ತು ಕಳೆ ಕೀಳುವಿಕೆ ಸುರಕ್ಷಿತ.",
    coordinates: "ಹೊಲದ ನಿರ್ದೇಶಾಂಕಗಳು",
    gps_detect_prompt: "ಪಿನ್ ಕೋಡ್ ನಮೂದಿಸಿ ಅಥವಾ GPS ಬಳಸಿ",
    syncing: "ಸ್ಥಳವನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    detected_location: "ಸ್ಥಳ ದಾಖಲಾಗಿದೆ",
    state_label: "ರಾಜ್ಯ",
    district_label: "ಜಿಲ್ಲೆ",
    village_label: "ಗ್ರಾಮ / ತಾಲೂಕು (ಐಚ್ಛಿಕ)",
    district_placeholder: "ಜಿಲ್ಲೆ ನಮೂದಿಸಿ ಅಥವಾ ಪಿನ್ ಕೋಡ್ ಬಳಸಿ",
    village_placeholder: "ಗ್ರಾಮ ಅಥವಾ ತಾಲೂಕು ನಮೂದಿಸಿ",
    current_crop_label: "ಪ್ರಸ್ತುತ ಬೆಳೆ",
    previous_crop_label: "ಹಿಂದಿನ ಋತುವಿನ ಬೆಳೆ (ಬೆಳೆ ಸರದಿಗಾಗಿ)",
    select_crop_empty: "-- ಆಯ್ಕೆಮಾಡಿ (ಖಾಲಿ ಹೊಲ / ಹೊಸ ಬೆಳೆ ಯೋಜನೆ) --",
    select_prev_crop_empty: "-- ಆಯ್ಕೆಮಾಡಿ (ಯಾವುದೂ ಇಲ್ಲ / ಬಂಜರು) --",
    custom_crop_opt: "✍️ ಇತರ ಬೆಳೆ...",
    fallow_opt: "ಯಾವುದೂ ಇಲ್ಲ / ಬಂಜರು",
    affected_crop_title: "ಬಾಧಿತ ಬೆಳೆ (ಐಚ್ಛಿಕ)",
    auto_detect_crop_opt: "-- ಚಿತ್ರದಿಂದ ಬೆಳೆ ಪತ್ತೆಹಚ್ಚಿ (ಜೆಮಿನಿ) --",
    growth_stage_label: "ಬೆಳೆಯ ಹಂತ (ಐಚ್ಛಿಕ)",
    auto_detect_stage_opt: "-- ಚಿತ್ರದಿಂದ ಹಂತ ಪತ್ತೆಹಚ್ಚಿ --",
    stage_seedling: "ಸಸಿ ಹಂತ (0-20 ದಿನಗಳು)",
    stage_vegetative: "ಸಸ್ಯಕ ಬೆಳವಣಿಗೆ",
    stage_flowering: "ಹೂಬಿಡುವ ಹಂತ",
    stage_pod_filling: "ಕಾಯಿ / ಧಾನ್ಯ ತುಂಬುವ ಹಂತ",
    stage_maturity: "ಕಟಾವಿನ ಹಂತ",
    observed_symptoms_title: "ಕಂಡುಬಂದ ಲಕ್ಷಣಗಳು (ಐಚ್ಛಿಕ)",
    select_symptom_opt: "-- ಪಟ್ಟಿಯಿಂದ ಲಕ್ಷಣ ಆಯ್ಕೆಮಾಡಿ --",
    additional_notes: "ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ (ಐಚ್ಛಿಕ)",
    notes_placeholder: "ಉದಾ. ಮಳೆಯ ನಂತರ ಎಲೆಗಳು ಹಳದಿಯಾಗಿವೆ",
    ndmi_label_short: "ಎಲೆಗಳ ತೇವಾಂಶ (NDMI)",
    ndvi_label_short: "ಬೆಳೆಯ ಆರೋಗ್ಯ & ಹಸುರು (NDVI)",
    water_stress: "ನೀರಿನ ಒತ್ತಡ",
    biomass_status: "ಬಯೋಮಾಸ್ ಸಾಂದ್ರತೆ",
    status_adequate: "ಸಾಕಷ್ಟು ತೇವಾಂಶ",
    farm_explainer_title: "ನಿಖರವಾದ ಜಮೀನಿನ ಸ್ಥಳ ಮತ್ತು ಗಡಿಗಳು",
    farm_explainer_desc: "6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್ ಹಾಕಿ ಅಥವಾ GPS ಬಳಸಿ. ನಕ್ಷೆಯ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ ಹೊಲದ ಗಡಿಗಳನ್ನು ಗುರುತಿಸಿ.",
    advice_explainer_title: "ಕ್ಷೇತ್ರ ಯೋಜನೆ ಮತ್ತು ಉಪಗ್ರಹ ವಿಶ್ಲೇಷಣೆ",
    advice_explainer_desc: "ಸೆಂಟಿನೆಲ್-2 ಉಪಗ್ರಹ ಆಧಾರಿತ ಬೆಳೆ ತೇವಾಂಶ ಮತ್ತು ಜೆಮಿನಿ ನೈಸರ್ಗಿಕ ಕೃಷಿ ಯೋಜನೆ.",
    diagnose_explainer_title: "ಡಿಜಿಟಲ್ ಬೆಳೆ ಡಾಕ್ಟರ್",
    diagnose_explainer_desc: "ಜೆಮಿನಿ AI ಮೂಲಕ ಎಲೆಗಳ ರೋಗಲಕ್ಷಣಗಳ ಪರಿಶೀಲನೆ ಮತ್ತು ಸಾವಯವ ಪರಿಹಾರಗಳು.",
    tap_photo_prompt: "ಬಾಧಿತ ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    photo_format_hint: "PNG, JPG ಅಥವಾ WebP ಬೆಂಬಲಿತವಾಗಿದೆ",
    visible_findings_title: "ಎಲೆಗಳ ಮೇಲೆ ಕಂಡುಬರುವ ಲಕ್ಷಣಗಳು",
    plausible_causes_title: "ಸಾಧ್ಯವಾದ ಕಾರಣಗಳು",
    safe_next_steps_title: "ಸುರಕ್ಷಿತ ಸಾವಯವ ಪರಿಹಾರಗಳು ಮತ್ತು ಮುಂದಿನ ಹಂತಗಳು",
    uncertainty_note_title: "ಅನಿಶ್ಚಿತತೆಯ ಟಿಪ್ಪಣಿ",
    escalated_badge: "👨‍🔬 ಕೃಷಿ ತಜ್ಞರಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ",
    analyzing_leaf: "ಎಲೆಯ ರೋಗ ತಪಾಸಣೆ ನಡೆಯುತ್ತಿದೆ...",
    analyzing_leaf_desc: "ಜೆಮಿನಿ ವಿಷನ್ ಮೂಲಕ ಕೀಟ ಮತ್ತು ರೋಗಲಕ್ಷಣಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    add_farm_first: "ಮೊದಲು ಜಮೀನಿನ ವಿವರ ಸೇರಿಸಿ",
    add_farm_first_desc: "ಬೆಳೆ ರೋಗನಿರ್ಣಯವು ನೇರವಾಗಿ ನಿಮ್ಮ ಜಮೀನಿನ ವಿವರಗಳಿಗೆ ಲಿಂಕ್ ಆಗಿದೆ.",
    evidence_strip_title: "ವೀಕ್ಷಣೆ ಸಮಯ",
    latest_sat_scene: "ಇತ್ತೀಚಿನ ಸೆಂಟಿನೆಲ್-2 ಉಪಗ್ರಹ ದೃಶ್ಯ",
    latest_weather_obs: "ನೇರ ಹವಾಮಾನ ವೀಕ್ಷಣೆ",
    soil_profile_title: "ಮಣ್ಣಿನ ಪೋಷಕಾಂಶಗಳ ವಿವರ",
    sowing_window: "ಬಿತ್ತನೆ ಸನ್ನದ್ಧತೆ",
    spraying_window: "ಸಿಂಪಡಣೆ ಕಿಟಕಿ",
    irrigation_advisory: "ನೀರಾವರಿ ಸಲಹೆ",
    drainage_alert: "ನೀರು ನಿಲ್ಲುವ ಅಪಾಯ",
    table_color: "ಬಣ್ಣ",
    table_zone: "ವಲಯ",
    table_status: "ಬೆಳೆ ಸ್ಥಿತಿ",
    table_range: "ಮೌಲ್ಯ ಶ್ರೇಣಿ",
    table_area: "ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)",
    table_share: "ಪಾಲು (%)",
    table_median: "ಮಧ್ಯಸ್ಥ",
    geopard_title: "ವರ್ಗೀಕೃತ ಹೊಲದ ಸ್ಥಿತಿ ನಕ್ಷೆ",
    field_narrative_title: "ಉಪಗ್ರಹ ಕ್ಷೇತ್ರ ಸಾರಾಂಶ",
    optimal_window: "ಅತ್ಯುತ್ತಮ ಸಮಯ",
    caution_window: "ಎಚ್ಚರಿಕೆ / ಮಧ್ಯಮ",
    avoid_window: "ಮುಂದೂಡಿ / ನಿಲ್ಲಿಸಿ",
    crop_rec_title: "ವೈಜ್ಞಾನಿಕ ಬಹು-ಅಂಶ ಬೆಳೆ ಶಿಫಾರಸು ಎಂಜಿನ್",
    crop_rec_sub: "ಮಣ್ಣಿನ ವಿಧ, ನೀರಿನ ಲಭ್ಯತೆ, 7 ದಿನಗಳ ಮಳೆ ಮುನ್ಸೂಚನೆ ಮತ್ತು ಬೆಳೆ ಸರದಿಯ ಆಧಾರದ ಮೇಲೆ ನಿಖರ ಶಿಫಾರಸು.",
    rec_crops_heading: "ನಿಮ್ಮ ಹೊಲಕ್ಕೆ ಸೂಕ್ತವಾದ ಶಿಫಾರಸು ಮಾಡಲಾದ ಬೆಳೆಗಳು",
    unsuitable_crops_heading: "ಅನನುಕೂಲಕರ / ಹೆಚ್ಚಿನ ಅಪಾಯದ ಬೆಳೆಗಳು",
    match_score: "ಹೊಂದಾಣಿಕೆಯ ಸ್ಕೋರ್",
    evidence_cov: "ಸಾಕ್ಷ್ಯ ವ್ಯಾಪ್ತಿ",
    decision_factors: "ವೈಜ್ಞಾನಿಕ ನಿರ್ಧಾರದ ಅಂಶಗಳು ಮತ್ತು ವಿವರಣೆ",
    data_used: "ಬಳಸಿದ ಡೇಟಾ",
    reasoning: "ಕೃಷಿ-ವೈಜ್ಞಾನಿಕ ಕಾರಣ",
    remedy: "ಪರಿಹಾರ ಕ್ರಮ / ಸಲಹೆ",
    sources_badge: "ಬಳಸಿದ ಅಧಿಕೃತ ಡೇಟಾ ಮೂಲಗಳು",
    loading_crop_recs: "ಹೊಲಕ್ಕೆ ಸೂಕ್ತವಾದ ಬೆಳೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    no_crops_found: "ಈ ಋತುವಿನಲ್ಲಿ ಮತ್ತು ನೀರಿನ ಸೌಲಭ್ಯಕ್ಕೆ ಯಾವುದೇ ಬೆಳೆ ಹೊಂದಾಣಿಕೆಯಾಗಿಲ್ಲ.",
    why_unsuitable: "ಈ ಬೆಳೆಯನ್ನು ಏಕೆ ಶಿಫಾರಸು ಮಾಡಲಾಗಿಲ್ಲ:",
    view_factors_btn: "ನಿರ್ಧಾರದ ಅಂಶಗಳ ವಿವರಗಳನ್ನು ನೋಡಿ",
    hide_factors_btn: "ವಿವರಗಳನ್ನು ಮರೆಮಾಡಿ",
    view_unsuitable_btn: "ಅನನುಕೂಲಕರ ಬೆಳೆಗಳನ್ನು ನೋಡಿ",
    hide_unsuitable_btn: "ಅನನುಕೂಲಕರ ಬೆಳೆಗಳನ್ನು ಮರೆಮಾಡಿ",
    practices_recommended: "ಶಿಫಾರಸು ಮಾಡಲಾದ ಸಾವಯವ ಕೃಷಿ ವಿಧಾನಗಳು",
    step_farm: "1. ಜಮೀನಿನ ಗಡಿ",
    step_weather: "2. ಸ್ಥಳೀಯ ಹವಾಮಾನ",
    step_soil: "3. ಮಣ್ಣಿನ ಆರೋಗ್ಯ",
    step_crops: "4. ಬೆಳೆ ಶಿಫಾರಸು",
    step_advice: "5. ಕಾರ್ಯ ಯೋಜನೆ",
    plant_doctor: "ಬೆಳೆ ವೈದ್ಯ",
    btn_proceed_weather: "ಸ್ಥಳೀಯ ಹವಾಮಾನ ನೋಡಿ →",
    btn_proceed_soil: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ವಿವರಗಳು (ಐಚ್ಛಿಕ) →",
    btn_skip_soil: "ಮಣ್ಣಿನ ಪರೀಕ್ಷೆ ಬಿಟ್ಟು ಬೆಳೆಗಳನ್ನು ನೋಡಿ →",
    btn_proceed_crops: "ಬೆಳೆ ಶಿಫಾರಸುಗಳನ್ನು ನೋಡಿ →",
    btn_proceed_plan: "ಕಾರ್ಯ ಯೋಜನೆ ನೋಡಿ →",
    btn_proceed_doctor: "ಬೆಳೆ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ →",
    btn_back_farm: "← ಹೊಲದ ವಿವರಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    btn_back_weather: "← ಹವಾಮಾನಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    btn_back_soil: "← ಮಣ್ಣಿನ ಆರೋಗ್ಯಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    btn_back_crops: "← ಬೆಳೆ ಶಿಫಾರಸಿಗೆ ಹಿಂತಿರುಗಿ",
    btn_back_plan: "← ಕಾರ್ಯ ಯೋಜನೆಗೆ ಹಿಂತಿರುಗಿ",
    pincode_label: "ಪಿನ್ ಕೋಡ್ ಹುಡುಕಿ",
    pincode_placeholder: "6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್ ನಮೂದಿಸಿ (ಉದಾ. 431203)",
    pincode_btn: "ಸ್ಥಳ ಹುಡುಕಿ",
    pincode_searching: "ಪಿನ್ ಕೋಡ್ ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    plot_farm_boundary: "ಜಮೀನಿನ ಗಡಿ ಗುರುತಿಸುವಿಕೆ",
    plot_helper_tip: "ನಕ್ಷೆಯ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ 3 ರಿಂದ 5 ಮೂಲೆಗಳನ್ನು ಗುರುತಿಸಿ. ಎಕರೆ ವಿಸ್ತೀರ್ಣ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ.",
    plot_auto_1ac: "1 ಎಕರೆ ಬಾಕ್ಸ್",
    plot_auto_2ac: "2.5 ಎಕರೆ ಬಾಕ್ಸ್",
    plot_clear: "ಬಿಂದುಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ"
  }
};

