import { Locale } from "../types";

/** Text for the market, crowding and profit screens; merged into `copy` in localization.ts. */
export const marketCopy: Record<Locale, Record<string, string>> = {
  "en-IN": {
    market_accuracy: "Checked on the last {n} seasons: forecast was off by {err}% on average", market_yield_title: "Yield in the district, by year", market_forecast: "forecast", market_yield_note: "Forecast {kg} kg/ha for the coming season (trend {trend} kg/ha a year; checked on past years: off by {err}% on average)", market_other: "Other",
    market_trend: "Price trend and forecast", market_trend_line: "Monthly mandi price", market_trend_band: "Expected at harvest", market_crowd_village: "{same} of {total} planned farms in {village} chose this crop",
    nav_market: "Market", step_market: "5. Market & Profit", step_advice_6: "6. Field Plan",
    market_title: "Market price & profit", market_sub: "Past mandi prices, how many farmers near you grow the same crop, and what your field can earn.",
    market_not_covered: "Market prices and profit are available for {districts} for now.",
    market_pick_crop: "Crop", market_lookback: "Compare with past", market_seasons: "{n} seasons",
    market_expected_price: "Expected price at harvest", market_per_qtl: "/quintal", market_range: "likely {low} – {high}",
    market_last_season: "Last season", market_msp: "MSP", market_frp: "FRP (mill price)", market_below_msp: "Mandi price was below MSP in {n} of the last {m} seasons.",
    market_sell_in: "Selling months", market_live_now: "Now in your district's mandis", market_live_detail: "median of {n} price reports, last {d} days",
    market_past_prices: "Harvest-time price, past seasons", market_month_profile: "Which month pays best", market_best_month: "Historically {month} paid {gain} more than harvest time — store and sell then if you can.",
    market_crowding: "Farmers near you", market_crowd_high: "Crowded — many farmers are planting this", market_crowd_normal: "Normal planting", market_crowd_low: "Less competition than usual",
    market_crowd_taluka: "{same} of {total} planned farms in {taluka} taluka chose this crop", market_crowd_district: "{same} of {total} planned farms in {district} district chose this crop",
    market_crowd_apy: "District area under this crop in {year}: {area} ha ({change} vs 5-year average)", market_crowd_sample: "includes {n} sample entries",
    market_crowd_effect: "Expected price effect of this crowding: {effect}", market_plan_btn: "I'll grow this crop", market_plan_saved: "Saved — your choice is counted (anonymously) for farmers near you.",
    market_apmc: "Mandis (APMC) near you", market_apmc_price: "Harvest price", market_apmc_arrivals: "Arrivals", market_apmc_distance: "Distance",
    market_sim_title: "Profit simulator", market_sim_sub: "{runs} simulated seasons with real ups and downs of yield and price.",
    market_area: "Area", market_acres: "acres", market_price_override: "Your price (₹/qtl)", market_cost_override: "Your cost (₹/acre)", market_yield_override: "Your yield (qtl/acre)",
    market_msp_toggle: "Assume I can sell at MSP (government procurement)", market_run: "Simulate", market_auto: "auto",
    market_production: "Production", market_revenue: "Income", market_cost: "Cost", market_profit: "Profit", market_low: "bad year", market_typical: "typical", market_high: "good year",
    market_loss_chance: "Chance of loss", market_breakeven: "Break-even price", market_transport: "Transport to mandi",
    market_assumptions: "How this is worked out", market_yield_basis: "Yield {y} qtl/acre — {source}", market_cost_basis: "Cost ₹{c}/acre — {basis}", market_estimate: "estimate",
    market_sources: "Data sources", market_profit_per_acre: "Profit / acre", market_open_sim: "Market & profit →", market_compare: "Compare crops", market_qtl: "qtl",
    market_profit_dist: "How often each profit came up", market_no_data: "Not enough market data for this crop and season.",
    market_model_note: "Price = median harvest price of the chosen seasons, raised {infl}% a year, adjusted for crowding (price falls {flex}% per 10% more supply). Yield from the district's recent years, adjusted for your water and soil.",
    btn_back_crops: "← Back to Crops", btn_to_market: "Market & Profit →",
  },
  "hi-IN": {
    market_accuracy: "पिछले {n} सीज़न पर जांचा: अनुमान औसतन {err}% अलग रहा", market_yield_title: "ज़िले की उपज, वर्षवार", market_forecast: "अनुमान", market_yield_note: "आने वाले सीज़न का अनुमान {kg} किग्रा/हे. (रुझान {trend} किग्रा/हे. प्रति वर्ष; पिछले वर्षों पर औसत अंतर {err}%)", market_other: "अन्य",
    market_trend: "भाव का रुझान और अनुमान", market_trend_line: "मासिक मंडी भाव", market_trend_band: "कटाई पर अनुमान", market_crowd_village: "{village} में {total} में से {same} किसानों ने यह फसल चुनी",
    nav_market: "बाज़ार", step_market: "5. बाज़ार व मुनाफा", step_advice_6: "6. खेत योजना",
    market_title: "बाज़ार भाव और मुनाफा", market_sub: "पिछले मंडी भाव, आसपास कितने किसान यही फसल लगा रहे हैं, और आपके खेत से कितनी कमाई हो सकती है।",
    market_not_covered: "बाज़ार भाव और मुनाफा अभी {districts} के लिए उपलब्ध है।",
    market_pick_crop: "फसल", market_lookback: "पिछले से तुलना", market_seasons: "{n} सीज़न",
    market_expected_price: "कटाई पर अनुमानित भाव", market_per_qtl: "/क्विंटल", market_range: "संभावित {low} – {high}",
    market_last_season: "पिछला सीज़न", market_msp: "MSP", market_frp: "FRP (मिल भाव)", market_below_msp: "पिछले {m} में से {n} सीज़न में मंडी भाव MSP से कम रहा।",
    market_sell_in: "बिक्री के महीने", market_live_now: "अभी आपके ज़िले की मंडियों में", market_live_detail: "{n} भाव रिपोर्ट का मध्य, पिछले {d} दिन",
    market_past_prices: "कटाई के समय भाव, पिछले सीज़न", market_month_profile: "किस महीने सबसे अच्छा भाव", market_best_month: "पहले {month} में कटाई से {gain} ज़्यादा भाव मिला — संभव हो तो भंडारण कर तब बेचें।",
    market_crowding: "आसपास के किसान", market_crowd_high: "भीड़ — बहुत किसान यही लगा रहे हैं", market_crowd_normal: "सामान्य बुवाई", market_crowd_low: "सामान्य से कम प्रतिस्पर्धा",
    market_crowd_taluka: "{taluka} तालुका में {total} में से {same} किसानों ने यह फसल चुनी", market_crowd_district: "{district} ज़िले में {total} में से {same} किसानों ने यह फसल चुनी",
    market_crowd_apy: "{year} में ज़िले में इस फसल का क्षेत्र: {area} हे. (5 साल औसत से {change})", market_crowd_sample: "{n} नमूना प्रविष्टियाँ शामिल",
    market_crowd_effect: "इस भीड़ का भाव पर अनुमानित असर: {effect}", market_plan_btn: "मैं यह फसल लगाऊँगा", market_plan_saved: "सहेजा गया — आपकी पसंद आसपास के किसानों के लिए (गुमनाम) गिनी गई।",
    market_apmc: "आपके पास की मंडियाँ (APMC)", market_apmc_price: "कटाई भाव", market_apmc_arrivals: "आवक", market_apmc_distance: "दूरी",
    market_sim_title: "मुनाफा सिम्युलेटर", market_sim_sub: "उपज और भाव के असली उतार-चढ़ाव के साथ {runs} सीज़न का अनुमान।",
    market_area: "क्षेत्र", market_acres: "एकड़", market_price_override: "आपका भाव (₹/क्विंटल)", market_cost_override: "आपका खर्च (₹/एकड़)", market_yield_override: "आपकी उपज (क्विंटल/एकड़)",
    market_msp_toggle: "मान लें कि MSP पर बेच सकता हूँ (सरकारी खरीद)", market_run: "गणना करें", market_auto: "स्वतः",
    market_production: "उत्पादन", market_revenue: "आय", market_cost: "खर्च", market_profit: "मुनाफा", market_low: "खराब साल", market_typical: "सामान्य", market_high: "अच्छा साल",
    market_loss_chance: "नुकसान की संभावना", market_breakeven: "बराबरी भाव", market_transport: "मंडी तक ढुलाई",
    market_assumptions: "गणना कैसे हुई", market_yield_basis: "उपज {y} क्विंटल/एकड़ — {source}", market_cost_basis: "खर्च ₹{c}/एकड़ — {basis}", market_estimate: "अनुमान",
    market_sources: "डेटा स्रोत", market_profit_per_acre: "मुनाफा / एकड़", market_open_sim: "बाज़ार व मुनाफा →", market_compare: "फसलों की तुलना", market_qtl: "क्विंटल",
    market_profit_dist: "कौन सा मुनाफा कितनी बार आया", market_no_data: "इस फसल और सीज़न का पर्याप्त बाज़ार डेटा नहीं है।",
    market_model_note: "भाव = चुने गए सीज़न का मध्य कटाई भाव, हर साल {infl}% बढ़ाकर, भीड़ के अनुसार समायोजित (10% ज़्यादा आपूर्ति पर भाव {flex}% गिरता है)। उपज ज़िले के हाल के वर्षों से, आपके पानी और मिट्टी के अनुसार।",
    btn_back_crops: "← फसलों पर वापस", btn_to_market: "बाज़ार व मुनाफा →",
  },
  "mr-IN": {
    market_accuracy: "मागील {n} हंगामांवर तपासले: अंदाज सरासरी {err}% फरकाने", market_yield_title: "जिल्ह्यातील उत्पादन, वर्षनिहाय", market_forecast: "अंदाज", market_yield_note: "येत्या हंगामाचा अंदाज {kg} किलो/हे. (कल {trend} किलो/हे. प्रति वर्ष; मागील वर्षांवर सरासरी फरक {err}%)", market_other: "इतर",
    market_trend: "भावाचा कल आणि अंदाज", market_trend_line: "मासिक बाजारभाव", market_trend_band: "काढणीवेळचा अंदाज", market_crowd_village: "{village} मध्ये {total} पैकी {same} शेतकऱ्यांनी हे पीक निवडले",
    nav_market: "बाजार", step_market: "५. बाजार व नफा", step_advice_6: "६. शेत योजना",
    market_title: "बाजारभाव आणि नफा", market_sub: "मागील बाजारभाव, तुमच्या भागात किती शेतकरी हेच पीक घेत आहेत, आणि तुमच्या शेतातून किती कमाई होऊ शकते.",
    market_not_covered: "बाजारभाव आणि नफा सध्या {districts} साठी उपलब्ध आहे.",
    market_pick_crop: "पीक", market_lookback: "मागील हंगामांशी तुलना", market_seasons: "{n} हंगाम",
    market_expected_price: "काढणीवेळी अपेक्षित भाव", market_per_qtl: "/क्विंटल", market_range: "बहुधा {low} – {high}",
    market_last_season: "मागील हंगाम", market_msp: "हमीभाव", market_frp: "FRP (कारखाना दर)", market_below_msp: "मागील {m} पैकी {n} हंगामांत बाजारभाव हमीभावापेक्षा कमी होता.",
    market_sell_in: "विक्रीचे महिने", market_live_now: "सध्या तुमच्या जिल्ह्यातील बाजार समित्यांत", market_live_detail: "{n} भाव नोंदींचा मध्य, मागील {d} दिवस",
    market_past_prices: "काढणीवेळचा भाव, मागील हंगाम", market_month_profile: "कोणत्या महिन्यात सर्वोत्तम भाव", market_best_month: "पूर्वी {month} मध्ये काढणीपेक्षा {gain} जास्त भाव मिळाला — शक्य असल्यास साठवून तेव्हा विका.",
    market_crowding: "तुमच्या भागातील शेतकरी", market_crowd_high: "गर्दी — अनेक शेतकरी हेच पीक घेत आहेत", market_crowd_normal: "नेहमीसारखी लागवड", market_crowd_low: "नेहमीपेक्षा कमी स्पर्धा",
    market_crowd_taluka: "{taluka} तालुक्यात {total} पैकी {same} शेतकऱ्यांनी हे पीक निवडले", market_crowd_district: "{district} जिल्ह्यात {total} पैकी {same} शेतकऱ्यांनी हे पीक निवडले",
    market_crowd_apy: "{year} मध्ये जिल्ह्यात या पिकाखालील क्षेत्र: {area} हे. (५ वर्षांच्या सरासरीपेक्षा {change})", market_crowd_sample: "{n} नमुना नोंदी समाविष्ट",
    market_crowd_effect: "या गर्दीचा भावावर अंदाजे परिणाम: {effect}", market_plan_btn: "मी हे पीक घेणार", market_plan_saved: "जतन केले — तुमची निवड भागातील शेतकऱ्यांसाठी (नाव न दाखवता) मोजली.",
    market_apmc: "जवळच्या बाजार समित्या (APMC)", market_apmc_price: "काढणीवेळ भाव", market_apmc_arrivals: "आवक", market_apmc_distance: "अंतर",
    market_sim_title: "नफा सिम्युलेटर", market_sim_sub: "उत्पादन व भावाच्या खऱ्या चढ-उतारांसह {runs} हंगामांचा अंदाज.",
    market_area: "क्षेत्र", market_acres: "एकर", market_price_override: "तुमचा भाव (₹/क्विंटल)", market_cost_override: "तुमचा खर्च (₹/एकर)", market_yield_override: "तुमचे उत्पादन (क्विंटल/एकर)",
    market_msp_toggle: "हमीभावाने विक्री शक्य आहे असे धरा (शासकीय खरेदी)", market_run: "गणना करा", market_auto: "आपोआप",
    market_production: "उत्पादन", market_revenue: "उत्पन्न", market_cost: "खर्च", market_profit: "नफा", market_low: "वाईट वर्ष", market_typical: "साधारण", market_high: "चांगले वर्ष",
    market_loss_chance: "तोट्याची शक्यता", market_breakeven: "ना नफा ना तोटा भाव", market_transport: "बाजारापर्यंत वाहतूक",
    market_assumptions: "गणना कशी केली", market_yield_basis: "उत्पादन {y} क्विंटल/एकर — {source}", market_cost_basis: "खर्च ₹{c}/एकर — {basis}", market_estimate: "अंदाज",
    market_sources: "माहितीचे स्रोत", market_profit_per_acre: "नफा / एकर", market_open_sim: "बाजार व नफा →", market_compare: "पिकांची तुलना", market_qtl: "क्विंटल",
    market_profit_dist: "कोणता नफा किती वेळा आला", market_no_data: "या पिकासाठी व हंगामासाठी पुरेशी बाजार माहिती नाही.",
    market_model_note: "भाव = निवडलेल्या हंगामांचा मध्य काढणी भाव, दरवर्षी {infl}% वाढवून, गर्दीनुसार समायोजित (१०% जास्त पुरवठ्याने भाव {flex}% कमी). उत्पादन जिल्ह्याच्या अलीकडील वर्षांवरून, तुमचे पाणी व मातीनुसार.",
    btn_back_crops: "← पिकांकडे परत", btn_to_market: "बाजार व नफा →",
  },
  "te-IN": {
    market_accuracy: "గత {n} సీజన్లపై పరీక్షించాం: అంచనా సగటున {err}% తేడా", market_yield_title: "జిల్లా దిగుబడి, సంవత్సరాల వారీగా", market_forecast: "అంచనా", market_yield_note: "రాబోయే సీజన్ అంచనా {kg} కిలో/హె. (ధోరణి ఏటా {trend} కిలో/హె.; గత సంవత్సరాలపై సగటు తేడా {err}%)", market_other: "ఇతర",
    market_trend: "ధర ధోరణి, అంచనా", market_trend_line: "నెలవారీ మండీ ధర", market_trend_band: "కోత సమయ అంచనా", market_crowd_village: "{village}లో {total}లో {same} మంది ఈ పంట ఎంచుకున్నారు",
    nav_market: "మార్కెట్", step_market: "5. మార్కెట్ & లాభం", step_advice_6: "6. పొలం ప్రణాళిక",
    market_title: "మార్కెట్ ధర & లాభం", market_sub: "గత మండీ ధరలు, మీ దగ్గర ఎంత మంది రైతులు ఇదే పంట వేస్తున్నారు, మీ పొలం ఎంత సంపాదించగలదు.",
    market_not_covered: "మార్కెట్ ధరలు, లాభం ప్రస్తుతం {districts} కోసం మాత్రమే.",
    market_pick_crop: "పంట", market_lookback: "గతంతో పోల్చండి", market_seasons: "{n} సీజన్లు",
    market_expected_price: "కోత సమయంలో అంచనా ధర", market_per_qtl: "/క్వింటాల్", market_range: "సుమారు {low} – {high}",
    market_last_season: "గత సీజన్", market_msp: "MSP", market_frp: "FRP (మిల్లు ధర)", market_below_msp: "గత {m} సీజన్లలో {n}లో మండీ ధర MSP కంటే తక్కువ.",
    market_sell_in: "అమ్మకం నెలలు", market_live_now: "ఇప్పుడు మీ జిల్లా మండీలలో", market_live_detail: "{n} ధర నివేదికల మధ్యస్థం, గత {d} రోజులు",
    market_past_prices: "కోత సమయ ధర, గత సీజన్లు", market_month_profile: "ఏ నెల ఎక్కువ ధర", market_best_month: "గతంలో {month}లో కోత సమయం కంటే {gain} ఎక్కువ ధర — వీలైతే నిల్వ చేసి అప్పుడు అమ్మండి.",
    market_crowding: "మీ దగ్గరి రైతులు", market_crowd_high: "రద్దీ — చాలా మంది ఇదే వేస్తున్నారు", market_crowd_normal: "సాధారణ సాగు", market_crowd_low: "సాధారణం కంటే తక్కువ పోటీ",
    market_crowd_taluka: "{taluka} తాలూకాలో {total}లో {same} మంది ఈ పంట ఎంచుకున్నారు", market_crowd_district: "{district} జిల్లాలో {total}లో {same} మంది ఈ పంట ఎంచుకున్నారు",
    market_crowd_apy: "{year}లో జిల్లాలో ఈ పంట విస్తీర్ణం: {area} హె. (5 ఏళ్ల సగటుతో {change})", market_crowd_sample: "{n} నమూనా నమోదులు ఉన్నాయి",
    market_crowd_effect: "ఈ రద్దీ వల్ల ధరపై అంచనా ప్రభావం: {effect}", market_plan_btn: "నేను ఈ పంట వేస్తాను", market_plan_saved: "సేవ్ అయింది — మీ ఎంపిక (పేరు లేకుండా) లెక్కించబడింది.",
    market_apmc: "మీ దగ్గరి మండీలు (APMC)", market_apmc_price: "కోత ధర", market_apmc_arrivals: "రాక", market_apmc_distance: "దూరం",
    market_sim_title: "లాభం సిమ్యులేటర్", market_sim_sub: "దిగుబడి, ధరల నిజమైన హెచ్చుతగ్గులతో {runs} సీజన్ల అంచనా.",
    market_area: "విస్తీర్ణం", market_acres: "ఎకరాలు", market_price_override: "మీ ధర (₹/క్వింటాల్)", market_cost_override: "మీ ఖర్చు (₹/ఎకరం)", market_yield_override: "మీ దిగుబడి (క్వింటాల్/ఎకరం)",
    market_msp_toggle: "MSPకి అమ్మగలనని అనుకోండి (ప్రభుత్వ కొనుగోలు)", market_run: "లెక్కించండి", market_auto: "ఆటో",
    market_production: "ఉత్పత్తి", market_revenue: "ఆదాయం", market_cost: "ఖర్చు", market_profit: "లాభం", market_low: "చెడ్డ సంవత్సరం", market_typical: "సాధారణ", market_high: "మంచి సంవత్సరం",
    market_loss_chance: "నష్టం అవకాశం", market_breakeven: "సమతుల్య ధర", market_transport: "మండీకి రవాణా",
    market_assumptions: "ఇలా లెక్కించాం", market_yield_basis: "దిగుబడి {y} క్వింటాల్/ఎకరం — {source}", market_cost_basis: "ఖర్చు ₹{c}/ఎకరం — {basis}", market_estimate: "అంచనా",
    market_sources: "సమాచార మూలాలు", market_profit_per_acre: "లాభం / ఎకరం", market_open_sim: "మార్కెట్ & లాభం →", market_compare: "పంటల పోలిక", market_qtl: "క్వింటాల్",
    market_profit_dist: "ఏ లాభం ఎన్నిసార్లు వచ్చింది", market_no_data: "ఈ పంట, సీజన్‌కు తగినంత మార్కెట్ సమాచారం లేదు.",
    market_model_note: "ధర = ఎంచుకున్న సీజన్ల మధ్యస్థ కోత ధర, ఏటా {infl}% పెంచి, రద్దీకి సర్దుబాటు (10% ఎక్కువ సరఫరాకు ధర {flex}% తగ్గుతుంది). దిగుబడి జిల్లా ఇటీవలి సంవత్సరాల నుండి.",
    btn_back_crops: "← పంటలకు వెనక్కి", btn_to_market: "మార్కెట్ & లాభం →",
  },
  "kn-IN": {
    market_accuracy: "ಕಳೆದ {n} ಹಂಗಾಮುಗಳಲ್ಲಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ: ಅಂದಾಜು ಸರಾಸರಿ {err}% ವ್ಯತ್ಯಾಸ", market_yield_title: "ಜಿಲ್ಲೆಯ ಇಳುವರಿ, ವರ್ಷವಾರು", market_forecast: "ಅಂದಾಜು", market_yield_note: "ಮುಂದಿನ ಹಂಗಾಮಿನ ಅಂದಾಜು {kg} ಕೆಜಿ/ಹೆ. (ಪ್ರವೃತ್ತಿ ವರ್ಷಕ್ಕೆ {trend} ಕೆಜಿ/ಹೆ.; ಹಿಂದಿನ ವರ್ಷಗಳಲ್ಲಿ ಸರಾಸರಿ ವ್ಯತ್ಯಾಸ {err}%)", market_other: "ಇತರ",
    market_trend: "ಬೆಲೆ ಪ್ರವೃತ್ತಿ ಮತ್ತು ಅಂದಾಜು", market_trend_line: "ಮಾಸಿಕ ಮಂಡಿ ಬೆಲೆ", market_trend_band: "ಕಟಾವಿನ ಅಂದಾಜು", market_crowd_village: "{village} ನಲ್ಲಿ {total} ರಲ್ಲಿ {same} ರೈತರು ಈ ಬೆಳೆ ಆರಿಸಿದ್ದಾರೆ",
    nav_market: "ಮಾರುಕಟ್ಟೆ", step_market: "5. ಮಾರುಕಟ್ಟೆ & ಲಾಭ", step_advice_6: "6. ಹೊಲದ ಯೋಜನೆ",
    market_title: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ & ಲಾಭ", market_sub: "ಹಿಂದಿನ ಮಂಡಿ ಬೆಲೆಗಳು, ನಿಮ್ಮ ಸುತ್ತ ಎಷ್ಟು ರೈತರು ಇದೇ ಬೆಳೆ ಬೆಳೆಯುತ್ತಿದ್ದಾರೆ, ನಿಮ್ಮ ಹೊಲ ಎಷ್ಟು ಗಳಿಸಬಹುದು.",
    market_not_covered: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಮತ್ತು ಲಾಭ ಸದ್ಯಕ್ಕೆ {districts} ಗೆ ಮಾತ್ರ.",
    market_pick_crop: "ಬೆಳೆ", market_lookback: "ಹಿಂದಿನದರೊಂದಿಗೆ ಹೋಲಿಕೆ", market_seasons: "{n} ಹಂಗಾಮು",
    market_expected_price: "ಕಟಾವಿನಲ್ಲಿ ಅಂದಾಜು ಬೆಲೆ", market_per_qtl: "/ಕ್ವಿಂಟಾಲ್", market_range: "ಸುಮಾರು {low} – {high}",
    market_last_season: "ಕಳೆದ ಹಂಗಾಮು", market_msp: "MSP", market_frp: "FRP (ಕಾರ್ಖಾನೆ ಬೆಲೆ)", market_below_msp: "ಕಳೆದ {m} ಹಂಗಾಮುಗಳಲ್ಲಿ {n} ರಲ್ಲಿ ಮಂಡಿ ಬೆಲೆ MSP ಗಿಂತ ಕಡಿಮೆ.",
    market_sell_in: "ಮಾರಾಟದ ತಿಂಗಳುಗಳು", market_live_now: "ಈಗ ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಮಂಡಿಗಳಲ್ಲಿ", market_live_detail: "{n} ಬೆಲೆ ವರದಿಗಳ ಮಧ್ಯಮ, ಕಳೆದ {d} ದಿನ",
    market_past_prices: "ಕಟಾವು ಸಮಯದ ಬೆಲೆ, ಹಿಂದಿನ ಹಂಗಾಮುಗಳು", market_month_profile: "ಯಾವ ತಿಂಗಳು ಉತ್ತಮ ಬೆಲೆ", market_best_month: "ಹಿಂದೆ {month} ನಲ್ಲಿ ಕಟಾವಿಗಿಂತ {gain} ಹೆಚ್ಚು ಬೆಲೆ — ಸಾಧ್ಯವಾದರೆ ಸಂಗ್ರಹಿಸಿ ಆಗ ಮಾರಿ.",
    market_crowding: "ನಿಮ್ಮ ಸುತ್ತಲಿನ ರೈತರು", market_crowd_high: "ಜನಸಂದಣಿ — ಅನೇಕರು ಇದೇ ಬೆಳೆಯುತ್ತಿದ್ದಾರೆ", market_crowd_normal: "ಸಾಮಾನ್ಯ ಬಿತ್ತನೆ", market_crowd_low: "ಸಾಮಾನ್ಯಕ್ಕಿಂತ ಕಡಿಮೆ ಪೈಪೋಟಿ",
    market_crowd_taluka: "{taluka} ತಾಲೂಕಿನಲ್ಲಿ {total} ರಲ್ಲಿ {same} ರೈತರು ಈ ಬೆಳೆ ಆರಿಸಿದ್ದಾರೆ", market_crowd_district: "{district} ಜಿಲ್ಲೆಯಲ್ಲಿ {total} ರಲ್ಲಿ {same} ರೈತರು ಈ ಬೆಳೆ ಆರಿಸಿದ್ದಾರೆ",
    market_crowd_apy: "{year} ರಲ್ಲಿ ಜಿಲ್ಲೆಯಲ್ಲಿ ಈ ಬೆಳೆಯ ವಿಸ್ತೀರ್ಣ: {area} ಹೆ. (5 ವರ್ಷದ ಸರಾಸರಿಗೆ {change})", market_crowd_sample: "{n} ಮಾದರಿ ನಮೂದುಗಳು ಸೇರಿವೆ",
    market_crowd_effect: "ಈ ಜನಸಂದಣಿಯ ಬೆಲೆ ಪರಿಣಾಮ ಅಂದಾಜು: {effect}", market_plan_btn: "ನಾನು ಈ ಬೆಳೆ ಬೆಳೆಯುತ್ತೇನೆ", market_plan_saved: "ಉಳಿಸಲಾಗಿದೆ — ನಿಮ್ಮ ಆಯ್ಕೆ (ಹೆಸರಿಲ್ಲದೆ) ಎಣಿಸಲಾಗಿದೆ.",
    market_apmc: "ಹತ್ತಿರದ ಮಂಡಿಗಳು (APMC)", market_apmc_price: "ಕಟಾವು ಬೆಲೆ", market_apmc_arrivals: "ಆವಕ", market_apmc_distance: "ದೂರ",
    market_sim_title: "ಲಾಭ ಸಿಮ್ಯುಲೇಟರ್", market_sim_sub: "ಇಳುವರಿ ಮತ್ತು ಬೆಲೆಯ ನಿಜವಾದ ಏರಿಳಿತಗಳೊಂದಿಗೆ {runs} ಹಂಗಾಮುಗಳ ಅಂದಾಜು.",
    market_area: "ವಿಸ್ತೀರ್ಣ", market_acres: "ಎಕರೆ", market_price_override: "ನಿಮ್ಮ ಬೆಲೆ (₹/ಕ್ವಿಂಟಾಲ್)", market_cost_override: "ನಿಮ್ಮ ವೆಚ್ಚ (₹/ಎಕರೆ)", market_yield_override: "ನಿಮ್ಮ ಇಳುವರಿ (ಕ್ವಿಂಟಾಲ್/ಎಕರೆ)",
    market_msp_toggle: "MSP ಗೆ ಮಾರಬಹುದು ಎಂದು ಭಾವಿಸಿ (ಸರ್ಕಾರಿ ಖರೀದಿ)", market_run: "ಲೆಕ್ಕ ಹಾಕಿ", market_auto: "ಸ್ವಯಂ",
    market_production: "ಉತ್ಪಾದನೆ", market_revenue: "ಆದಾಯ", market_cost: "ವೆಚ್ಚ", market_profit: "ಲಾಭ", market_low: "ಕೆಟ್ಟ ವರ್ಷ", market_typical: "ಸಾಮಾನ್ಯ", market_high: "ಒಳ್ಳೆಯ ವರ್ಷ",
    market_loss_chance: "ನಷ್ಟದ ಸಾಧ್ಯತೆ", market_breakeven: "ಸಮತೋಲನ ಬೆಲೆ", market_transport: "ಮಂಡಿಗೆ ಸಾಗಣೆ",
    market_assumptions: "ಹೀಗೆ ಲೆಕ್ಕ ಹಾಕಲಾಗಿದೆ", market_yield_basis: "ಇಳುವರಿ {y} ಕ್ವಿಂಟಾಲ್/ಎಕರೆ — {source}", market_cost_basis: "ವೆಚ್ಚ ₹{c}/ಎಕರೆ — {basis}", market_estimate: "ಅಂದಾಜು",
    market_sources: "ಮಾಹಿತಿ ಮೂಲಗಳು", market_profit_per_acre: "ಲಾಭ / ಎಕರೆ", market_open_sim: "ಮಾರುಕಟ್ಟೆ & ಲಾಭ →", market_compare: "ಬೆಳೆಗಳ ಹೋಲಿಕೆ", market_qtl: "ಕ್ವಿಂಟಾಲ್",
    market_profit_dist: "ಯಾವ ಲಾಭ ಎಷ್ಟು ಬಾರಿ ಬಂತು", market_no_data: "ಈ ಬೆಳೆ ಮತ್ತು ಹಂಗಾಮಿಗೆ ಸಾಕಷ್ಟು ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ ಇಲ್ಲ.",
    market_model_note: "ಬೆಲೆ = ಆಯ್ದ ಹಂಗಾಮುಗಳ ಮಧ್ಯಮ ಕಟಾವು ಬೆಲೆ, ವರ್ಷಕ್ಕೆ {infl}% ಏರಿಸಿ, ಜನಸಂದಣಿಗೆ ಹೊಂದಿಸಲಾಗಿದೆ (10% ಹೆಚ್ಚು ಪೂರೈಕೆಗೆ ಬೆಲೆ {flex}% ಇಳಿಕೆ). ಇಳುವರಿ ಜಿಲ್ಲೆಯ ಇತ್ತೀಚಿನ ವರ್ಷಗಳಿಂದ.",
    btn_back_crops: "← ಬೆಳೆಗಳಿಗೆ ಹಿಂದೆ", btn_to_market: "ಮಾರುಕಟ್ಟೆ & ಲಾಭ →",
  },
};
